import { useCallback, useMemo, useState } from 'react';
import { RefreshControl, StyleSheet, View } from 'react-native';
import { useTranslation } from 'react-i18next';
import { ApiError } from '@/src/core/api';
import { useAppTheme } from '@/src/core/theme';
import { permissions, useAuthorization } from '@/src/features/auth';
import { useAppReadOnly } from '@/src/shared/contexts/AppReadOnlyContext';
import { toApiPageNumber, useServerListState } from '@/src/shared/listing';
import { AppDataTable, type AppDataTableColumn, AppIconButton, AppListScreen, AppScreen, AppStateView, AppStatusBadge, AppText, ConfirmationDialog, showToast } from '@/src/shared/components';
import { OrganizationalStructureCard } from '../components/OrganizationalStructureCard';
import { OrganizationalStructureChart } from '../components/OrganizationalStructureChart';
import { OrganizationalStructureReportView } from '../components/OrganizationalStructureReportView';
import { OrganizationalStructureImportView } from '../components/import-data/OrganizationalStructureImportView';
import { OrganizationalStructureFilterButton } from '../components/OrganizationalStructureFilterButton';
import { JobDescriptionDecisionForm } from '../components/JobDescriptionDecisionForm';
import { OrganizationalStructureForm } from '../components/OrganizationalStructureForm';
import { useApproveJobDescription, useArchiveOrganizationalItem, useOrganizationalStructure, useRejectJobDescription, useRestoreOrganizationalItem, useSaveOrganizationalItem } from '../queries/use-organizational-structure';
import { type OrganizationalResource, type OrganizationalSearchField, type OrganizationalSearchOperator, type OrganizationalSortColumn, type OrganizationalStatus, type OrganizationalStructureItem, type OrganizationalStructureRequest } from '../types/organizational-structure';
import { canDecideJobDescription, getJobDescriptionStatusKey } from '../utils/job-description-status';

type FormMode = 'create' | 'edit' | 'view';
export function OrganizationalStructureManagementScreen({ resource }: { resource: OrganizationalResource }) {
  const { t } = useTranslation(); const { theme } = useAppTheme(); const { isReadOnly, notifyBlockedAction } = useAppReadOnly();
  const { allowed: viewAllowed } = useAuthorization({ requiredPermissions: [permissions.ViewOrganizationalStructure] });
  const { allowed: createAllowed } = useAuthorization({ requiredPermissions: [permissions.CreateOrganizationalStructure] });
  const { allowed: editAllowed } = useAuthorization({ requiredPermissions: [permissions.EditOrganizationalStructure] });
  const { allowed: deleteAllowed } = useAuthorization({ requiredPermissions: [permissions.DeleteOrganizationalStructure] });
  const { allowed: approveAllowed } = useAuthorization({ requiredPermissions: [permissions.ApproveJobDescriptions] });
  const canCreate = createAllowed && !isReadOnly; const canEdit = editAllowed && !isReadOnly; const canDelete = deleteAllowed && !isReadOnly;
  const [status, setStatus] = useState<OrganizationalStatus>('active'); const [searchField, setSearchField] = useState<OrganizationalSearchField>('all'); const [searchOperator, setSearchOperator] = useState<OrganizationalSearchOperator>('contains');
  const list = useServerListState<OrganizationalSortColumn, { status: OrganizationalStatus }>({ initialFilters: { status: 'active' }, initialPageSize: 5, initialSort: { columnId: 'nameEn', direction: 'ascending' } });
  const query = useOrganizationalStructure({ resource, pageNumber: toApiPageNumber(list.state.page), pageSize: list.state.pageSize, search: list.state.search, searchField, searchOperator, status, sortBy: list.state.sort?.columnId ?? 'nameEn', sortDirection: list.state.sort?.direction === 'descending' ? 'desc' : 'asc' });
  const saveMutation = useSaveOrganizationalItem(); const archiveMutation = useArchiveOrganizationalItem(); const restoreMutation = useRestoreOrganizationalItem(); const approveMutation = useApproveJobDescription(); const rejectMutation = useRejectJobDescription();
  const [mode, setMode] = useState<FormMode>('view'); const [selected, setSelected] = useState<OrganizationalStructureItem | null>(null); const [pendingArchive, setPendingArchive] = useState<OrganizationalStructureItem | null>(null);
  const [decisionMode, setDecisionMode] = useState<'approve' | 'reject' | null>(null); const [decisionItem, setDecisionItem] = useState<OrganizationalStructureItem | null>(null);
  const rows = query.data?.items ?? [];
  const open = useCallback((nextMode: FormMode, item: OrganizationalStructureItem | null) => { if (nextMode !== 'view' && isReadOnly) return notifyBlockedAction(); setMode(nextMode); setSelected(item); }, [isReadOnly, notifyBlockedAction]);
  const close = useCallback(() => { setSelected(null); setMode('view'); }, []);
  const save = useCallback(async (request: OrganizationalStructureRequest) => { try { await saveMutation.mutateAsync({ resource, id: mode === 'edit' ? selected?.id ?? null : null, request }); close(); showToast.success(t('organizationalStructure.saved')); } catch (error) { showToast.error(error, t('organizationalStructure.saveFailed')); } }, [close, mode, resource, saveMutation, selected?.id, t]);
  const restore = useCallback(async (item: OrganizationalStructureItem) => { try { await restoreMutation.mutateAsync({ resource, id: item.id }); showToast.success(t('organizationalStructure.restored')); } catch (error) { showToast.error(error, t('organizationalStructure.restoreFailed')); } }, [resource, restoreMutation, t]);
  const archive = useCallback(async () => { if (!pendingArchive) return; try { await archiveMutation.mutateAsync({ resource, id: pendingArchive.id }); setPendingArchive(null); showToast.success(t('organizationalStructure.archived')); } catch (error) { showToast.error(error, t('organizationalStructure.archiveFailed')); } }, [archiveMutation, pendingArchive, resource, t]);
  const decide = useCallback(async (values: { effectiveDate: string; expiryDate: string; reason: string }) => { if (!decisionItem || !decisionMode) return; try { if (decisionMode === 'approve') await approveMutation.mutateAsync({ id: decisionItem.id, effectiveDate: values.effectiveDate, expiryDate: values.expiryDate || undefined }); else await rejectMutation.mutateAsync({ id: decisionItem.id, reason: values.reason }); showToast.success(t(`organizationalStructure.decision.${decisionMode === 'approve' ? 'approved' : 'rejected'}`)); setDecisionMode(null); setDecisionItem(null); } catch (error) { showToast.error(error, t('organizationalStructure.decision.failed')); } }, [approveMutation, decisionItem, decisionMode, rejectMutation, t]);
  const openDecision = useCallback((nextMode: 'approve' | 'reject', item: OrganizationalStructureItem) => { if (isReadOnly) return notifyBlockedAction(); setDecisionMode(nextMode); setDecisionItem(item); }, [isReadOnly, notifyBlockedAction]);
  const parentName = useCallback((item: OrganizationalStructureItem) => item.positionCode ?? item.divisionNameEn ?? item.departmentNameEn ?? item.branchNameEn ?? t('organizationalStructure.currentCompany'), [t]);
  const columns = useMemo<AppDataTableColumn<OrganizationalStructureItem>[]>(() => [
    { id: 'code', header: t('organizationalStructure.fields.code'), width: 110, sortable: true, render: (item) => <AppText variant="bodySmall">{item.code}</AppText> },
    { id: 'nameEn', header: t('organizationalStructure.fields.nameEn'), width: 170, sortable: true, render: (item) => <AppText variant="bodySmall" weight="700">{item.nameEn}</AppText> },
    { id: 'nameAr', header: t('organizationalStructure.fields.nameAr'), width: 170, sortable: true, render: (item) => <AppText variant="bodySmall">{item.nameAr}</AppText> },
    { id: 'parent', header: t('organizationalStructure.fields.parent'), width: 160, sortable: true, render: (item) => <AppText variant="bodySmall">{parentName(item)}</AppText> },
    { id: 'status', header: t('organizationalStructure.fields.status'), width: 170, align: 'center', render: (item) => { const decisionStatus = getJobDescriptionStatusKey(item); return <View style={styles.statuses}><AppStatusBadge color={item.isDeleted ? theme.colors.warning : theme.colors.success} label={t(item.isDeleted ? 'organizationalStructure.status.archived' : 'organizationalStructure.status.active')} />{decisionStatus ? <AppStatusBadge color={theme.colors.primary} label={t(`organizationalStructure.jobDescriptionStatus.${decisionStatus}`)} /> : null}</View>; } },
    { id: 'actions', header: t('organizationalStructure.actions'), width: 240, align: 'center', render: (item) => <View style={styles.actions}><AppIconButton icon="eye-outline" label={t('organizationalStructure.view')} onPress={() => open('view', item)} />{canEdit && !item.isDeleted ? <AppIconButton icon="create-outline" label={t('organizationalStructure.edit')} onPress={() => open('edit', item)} /> : null}{canDelete ? <AppIconButton icon={item.isDeleted ? 'refresh-outline' : 'archive-outline'} label={t(item.isDeleted ? 'organizationalStructure.restore' : 'organizationalStructure.archive')} onPress={() => item.isDeleted ? void restore(item) : setPendingArchive(item)} /> : null}{approveAllowed && resource === 'job-descriptions' && canDecideJobDescription(item) ? <><AppIconButton icon="checkmark-circle-outline" label={t('organizationalStructure.decision.approve')} onPress={() => openDecision('approve', item)} /><AppIconButton icon="close-circle-outline" label={t('organizationalStructure.decision.reject')} onPress={() => openDecision('reject', item)} /></> : null}</View> },
  ], [approveAllowed, canDelete, canEdit, open, openDecision, parentName, resource, restore, t, theme.colors.primary, theme.colors.success, theme.colors.warning]);
  if (!viewAllowed) return <AppScreen><AppStateView message={t('organizationalStructure.permissionDenied')} state="error" /></AppScreen>;
  if (query.isLoading) return <AppScreen><AppStateView state="loading" /></AppScreen>;
  if (query.error) return <AppScreen><AppStateView message={errorMessage(query.error, t('organizationalStructure.loadFailed'))} onRetry={() => void query.refetch()} state="error" /></AppScreen>;
  return <AppScreen contentContainerStyle={styles.screen} edges={['left', 'right', 'bottom']} refreshControl={<RefreshControl colors={[theme.colors.primary]} onRefresh={() => void query.refetch()} refreshing={query.isRefetching} tintColor={theme.colors.primary} />}>
    <AppListScreen<OrganizationalStructureItem, 'table' | 'cards' | 'chart' | 'report' | 'import'> defaultView="table" emptyContent={<AppStateView message={t('organizationalStructure.empty')} state="empty" />} fillViewSelector filterControl={<OrganizationalStructureFilterButton field={searchField} onApply={(values) => { setSearchField(values.field); setSearchOperator(values.operator); setStatus(values.status); list.setPage(0); }} operator={searchOperator} resource={resource} status={status} />} isFetching={query.isFetching} items={rows} onSearchChange={(value) => list.setSearchInput(value)} searchActions={canCreate ? <AppIconButton color={theme.colors.onPrimary} icon="add-outline" label={t('organizationalStructure.add')} onPress={() => open('create', null)} size={22} style={({ pressed }) => ({ backgroundColor: theme.colors.primary, opacity: pressed ? 0.75 : 1 })} /> : null} searchPlaceholder={t(`organizationalStructure.resources.${resource}`)} searchValue={list.searchInput} serverPagination={{ onPageChange: list.setPage, onPageSizeChange: list.setPageSize, page: list.state.page, pageSize: list.state.pageSize, pageSizeOptions: [3, 5, 10], totalItems: query.data?.metaData.totalCount ?? 0 }} showResultCount={false} showViewLabels views={[
      { value: 'table', icon: 'grid-outline', label: t('multiView.table'), defaultPageSize: 5, render: (items) => <AppDataTable columns={columns} getRowKey={(item) => item.id} rows={items} showPagination={false} serverState={{ onPageChange: list.setPage, onPageSizeChange: list.setPageSize, onSortChange: (sort) => list.setSort(sort ? { columnId: sort.columnId as OrganizationalSortColumn, direction: sort.direction } : null), page: list.state.page, pageSize: list.state.pageSize, sort: list.state.sort, totalRows: query.data?.metaData.totalCount ?? 0 }} /> },
      { value: 'cards', icon: 'albums-outline', label: t('multiView.cards'), defaultPageSize: 3, scrollable: true, render: (items) => <View style={styles.cards}>{items.map((item, index) => <OrganizationalStructureCard active={index === 0} canApprove={approveAllowed && resource === 'job-descriptions'} canDelete={canDelete} canEdit={canEdit} item={item} key={item.id} onApprove={(value) => openDecision('approve', value)} onArchive={setPendingArchive} onEdit={(value) => open('edit', value)} onReject={(value) => openDecision('reject', value)} onRestore={(value) => void restore(value)} onView={(value) => open('view', value)} />)}</View> },
      { value: 'chart', icon: 'stats-chart-outline', label: t('multiView.chart'), paginate: false, renderWhenEmpty: true, scrollable: true, render: (items) => <OrganizationalStructureChart items={items} resource={resource} totalCount={query.data?.metaData.totalCount ?? 0} /> },
      { value: 'report', icon: 'document-text-outline', label: t('organizationalStructure.reportView'), paginate: false, renderWhenEmpty: true, scrollable: true, render: (items) => <OrganizationalStructureReportView items={items} resource={resource} totalCount={query.data?.metaData.totalCount ?? 0} /> },
      ...(canCreate ? [{ value: 'import' as const, icon: 'cloud-upload-outline' as const, label: t('organizationalStructure.importView'), paginate: false, renderWhenEmpty: true, scrollable: true, render: () => <OrganizationalStructureImportView resource={resource} /> }] : []),
    ]} />
    {selected || mode === 'create' ? <OrganizationalStructureForm item={selected} loading={saveMutation.isPending} mode={mode} onClose={close} onSave={save} resource={resource} /> : null}
    {decisionMode && decisionItem ? <JobDescriptionDecisionForm loading={approveMutation.isPending || rejectMutation.isPending} mode={decisionMode} onClose={() => { setDecisionMode(null); setDecisionItem(null); }} onSubmit={decide} /> : null}
    <ConfirmationDialog confirmLabel={t('organizationalStructure.archive')} description={t('organizationalStructure.archiveDescription', { name: pendingArchive?.nameEn ?? '' })} loading={archiveMutation.isPending} onCancel={() => setPendingArchive(null)} onConfirm={() => void archive()} title={t('organizationalStructure.archiveTitle')} tone="warning" visible={pendingArchive !== null} />
  </AppScreen>;
}
function errorMessage(error: unknown, fallback: string) { return error instanceof ApiError || error instanceof Error ? error.message || fallback : fallback; }
const styles = StyleSheet.create({ screen: { gap: 12, paddingVertical: 8 }, actions: { flexDirection: 'row', justifyContent: 'center' }, statuses: { gap: 4, alignItems: 'center' }, cards: { gap: 7 } });
