import { StyleSheet, View } from 'react-native';
import { useTranslation } from 'react-i18next';
import { useAppTheme } from '@/src/core/theme';
import { AppCard, AppIcon, AppIconButton, AppStatusBadge, AppText } from '@/src/shared/components';
import type { District } from '../types/district';

interface Props { district: District; canEdit: boolean; canDelete: boolean; selected: boolean; onEdit: (district: District) => void; onArchive: (district: District) => void; onRestore: (district: District) => void; onView: (district: District) => void; onToggleSelection: (district: District) => void; }
export function DistrictCard({ district, canEdit, canDelete, selected, onEdit, onArchive, onRestore, onView, onToggleSelection }: Props) {
  const { t } = useTranslation(); const { theme } = useAppTheme(); const archived = district.isDeleted;
  return <AppCard padding="sm" style={styles.card}><View style={styles.header}><View style={[styles.icon, { backgroundColor: theme.colors.surfaceMuted, borderRadius: theme.radius.sm }]}><AppIcon color={theme.colors.primary} name="location-outline" size={21} /></View><View style={styles.name}><AppText numberOfLines={1} variant="label">{district.nameEn}</AppText><AppText color="muted" numberOfLines={1} variant="bodySmall">{district.nameAr}</AppText></View><AppStatusBadge color={archived ? theme.colors.warning : theme.colors.success} label={t(archived ? 'districts.archived' : 'districts.active')} /></View><View style={styles.details}><AppText color="muted" variant="caption">{district.code} · {district.state.nameEn}</AppText><AppText color="muted" variant="caption">{t('districts.addressesCount', { count: district.addressesCount })}</AppText></View><View style={styles.actions}>{canDelete && !archived ? <AppIconButton icon={selected ? 'checkbox' : 'square-outline'} label={t('districts.selectDistrict', { name: district.nameEn })} onPress={() => onToggleSelection(district)} /> : null}<AppIconButton icon="eye-outline" label={t('districts.viewDistrict')} onPress={() => onView(district)} />{canEdit && !archived ? <AppIconButton icon="create-outline" label={t('districts.editDistrict')} onPress={() => onEdit(district)} /> : null}{canDelete ? <AppIconButton icon={archived ? 'refresh-outline' : 'archive-outline'} label={t(archived ? 'districts.restore' : 'districts.archive')} onPress={() => archived ? onRestore(district) : onArchive(district)} /> : null}</View></AppCard>;
}
const styles = StyleSheet.create({ card: { gap: 5 }, header: { flexDirection: 'row', alignItems: 'center', gap: 6 }, icon: { width: 36, height: 36, alignItems: 'center', justifyContent: 'center' }, name: { flex: 1, minWidth: 0, gap: 1 }, details: { gap: 2 }, actions: { flexDirection: 'row', justifyContent: 'flex-end' } });
