<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>ErpSystem.Modules.HR.Infrastructure</AssemblyName>
    <RootNamespace>ErpSystem.Modules.HR.Infrastructure</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AspNet.Security.OAuth.LinkedIn" />
    <PackageReference Include="ClosedXML" />
    <PackageReference Include="EFCore.BulkExtensions" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="Hangfire.AspNetCore" />
    <PackageReference Include="Hangfire.SqlServer" />
    <PackageReference Include="MailKit" />
    <PackageReference Include="Mapster" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Caching.Hybrid" />
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="QRCoder" />
    <PackageReference Include="Scrutor" />
    <PackageReference Include="Serilog.AspNetCore" />
    <PackageReference Include="Syncfusion.Blazor.SfPdfViewer" />
    <PackageReference Include="System.Data.SqlClient" />
    <PackageReference Include="System.Drawing.Common" />
    <PackageReference Include="System.Linq.Dynamic.Core" />
    <PackageReference Include="System.Security.Permissions" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ErpSystem.Modules.HR.Application\ErpSystem.Modules.HR.Application.csproj" />
    <ProjectReference Include="..\ErpSystem.Modules.HR.Domain\ErpSystem.Modules.HR.Domain.csproj" />
    <ProjectReference Include="..\..\Accounting\ErpSystem.Modules.Accounting.Contracts\ErpSystem.Modules.Accounting.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Templates\*.html">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
      <TargetPath>Templates\%(Filename)%(Extension)</TargetPath>
    </Content>
  </ItemGroup>
</Project>
