"use client";
import { useMemo } from "react";
import type { GridColDef } from "@mui/x-data-grid";
import { Box, MenuItem, Stack, TextField } from "@mui/material";
import { PageHeader } from "@/shared/components/navigation/header";
import { useServerListState } from "@/shared/hooks/useServerListState";
import { useAttendanceDevicePage, useRawPunches } from "../hooks/useAttendanceDeviceQueries";
import type { AttendanceDeviceSort, RawPunch } from "../types/attendanceDevices";
import { toAttendanceDeviceQuery } from "../utils/attendanceDeviceQuery";
import { AttendanceModuleLayout } from "../components/AttendanceModuleLayout";
import { RawGrid } from "../components/RawGrid";

type Filters = { deviceId: string; fromUtc: string; toUtc: string };
export default function AttendancePunchesPage() {
  const list = useServerListState<"occurredAtUtc" | "externalCode" | "deviceName" | "occurredAtDeviceLocal" | "pulledAtUtc", Filters>({ defaultColumn: "occurredAtUtc", defaultSortDirection: "DESC", defaultFilters: { deviceId: "", fromUtc: "", toUtc: "" }, defaultPageSize: 10 });
  const deviceList = useServerListState<AttendanceDeviceSort, Record<string, never>>({ defaultColumn: "name", defaultFilters: {}, defaultPageSize: 50 });
  const devices = useAttendanceDevicePage(useMemo(() => toAttendanceDeviceQuery(deviceList.state, ""), [deviceList.state]));
  const query = useMemo(() => ({ pageNumber: list.state.page + 1, pageSize: list.state.pageSize, deviceId: list.state.filters.deviceId ? Number(list.state.filters.deviceId) : undefined, externalCode: list.debouncedSearchValue || undefined, fromUtc: list.state.filters.fromUtc ? new Date(list.state.filters.fromUtc).toISOString() : undefined, toUtc: list.state.filters.toUtc ? new Date(list.state.filters.toUtc).toISOString() : undefined, sortBy: list.state.columnName, sortDirection: list.state.sortDirection.toLowerCase() as "asc" | "desc" }), [list.debouncedSearchValue, list.state]);
  const result = useRawPunches(query);
  const setFilter = (key: keyof Filters, value: string) => list.setFilters({ ...list.state.filters, [key]: value });
  const columns: GridColDef<RawPunch>[] = [{ field: "deviceName", headerName: "Device", minWidth: 150, flex: 1, sortable: true }, { field: "externalCode", headerName: "External code", minWidth: 135, flex: 1 }, { field: "name", headerName: "Name", minWidth: 140, flex: 1, sortable: false }, { field: "occurredAtDeviceLocal", headerName: "Device local time", minWidth: 180, sortable: true, valueFormatter: (value) => value ? new Date(value).toLocaleString() : "" }, { field: "occurredAtUtc", headerName: "UTC", minWidth: 180, sortable: true, valueFormatter: (value) => value ? new Date(value).toLocaleString() : "" }, { field: "verifyMode", headerName: "Verify mode", width: 110, sortable: false }, { field: "inOutMode", headerName: "In/out mode", width: 115, sortable: false }, { field: "workCode", headerName: "Work code", width: 100, sortable: false }];
  return <AttendanceModuleLayout><Box sx={{ minHeight: 0, display: "flex", flexDirection: "column", flex: 1, gap: 2 }}><PageHeader title="Raw attendance punches" subTitle="Original provider records. In/out mode is not an attendance decision." /><Stack direction={{ xs: "column", md: "row" }} spacing={1}><TextField select label="Device" value={list.state.filters.deviceId} onChange={(event) => setFilter("deviceId", event.target.value)} sx={{ minWidth: 220 }}><MenuItem value="">All devices</MenuItem>{devices.data?.items.map((device) => <MenuItem key={device.id} value={String(device.id)}>{device.name}</MenuItem>)}</TextField><TextField label="From" type="datetime-local" value={list.state.filters.fromUtc} onChange={(event) => setFilter("fromUtc", event.target.value)} slotProps={{ inputLabel: { shrink: true } }} /><TextField label="To" type="datetime-local" value={list.state.filters.toUtc} onChange={(event) => setFilter("toUtc", event.target.value)} slotProps={{ inputLabel: { shrink: true } }} /></Stack><RawGrid rows={result.data?.items ?? []} columns={columns} total={result.data?.metaData.totalCount ?? 0} page={list.state.page} pageSize={list.state.pageSize} loading={result.isLoading} fetching={result.isFetching} error={result.error} onRetry={() => void result.refetch()} onPaginationChange={(model) => { list.setPage(model.page); list.setPageSize(model.pageSize); }} sortModel={[{ field: list.state.columnName, sort: list.state.sortDirection.toLowerCase() as "asc" | "desc" }]} onSortChange={(model) => { const next = model[0]; if (next?.sort) list.setSort(next.field as "occurredAtUtc" | "externalCode" | "deviceName" | "occurredAtDeviceLocal" | "pulledAtUtc", next.sort.toUpperCase() as "ASC" | "DESC"); }} searchValue={list.state.searchValue} searchPlaceholder="Search external code" onSearchChange={list.setSearchValue} onReset={list.reset} /></Box></AttendanceModuleLayout>;
}
