import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { usePositionEnvelopeUseCases, useWorkforceBudgetUseCases } from '../../composition/use-workforce-planning-use-cases';
import type { BudgetSourcePlanPageQuery, PositionEnvelopePageQuery, RejectWorkforceBudgetAction, UpdateWorkforceBudgetRequest, WorkforceBudgetAction, WorkforceBudgetPageQuery, WorkforceBudgetRequest } from '../../domain/models/workforce-budget';
import { workforcePlanKeys } from './use-workforce-plans';

export const workforceBudgetKeys = { all: ['workforce-budgets'] as const, list: (query: WorkforceBudgetPageQuery) => [...workforceBudgetKeys.all, 'list', query] as const, detail: (id: number) => [...workforceBudgetKeys.all, 'detail', id] as const, sourcePlans: (query: object) => [...workforceBudgetKeys.all, 'source-plans', query] as const, sourcePlan: (planId: number) => [...workforceBudgetKeys.all, 'source-plan', planId] as const };
export const positionEnvelopeKeys = { all: ['position-envelopes'] as const, list: (query: object) => [...positionEnvelopeKeys.all, 'list', query] as const, detail: (id: number) => [...positionEnvelopeKeys.all, 'detail', id] as const };
export const useWorkforceBudgets = (query: WorkforceBudgetPageQuery) => { const useCases = useWorkforceBudgetUseCases(); return useQuery({ queryKey: workforceBudgetKeys.list(query), queryFn: () => useCases.getPage(query), placeholderData: previous => previous }); };
export const useWorkforceBudget = (id: number | null, enabled = true) => { const useCases = useWorkforceBudgetUseCases(); return useQuery({ queryKey: workforceBudgetKeys.detail(id ?? 0), queryFn: () => useCases.getById(id!), enabled: enabled && !!id }); };
export const useBudgetSourcePlans = (query: BudgetSourcePlanPageQuery, enabled = true) => { const useCases = useWorkforceBudgetUseCases(); return useQuery({ queryKey: workforceBudgetKeys.sourcePlans(query), queryFn: () => useCases.getSourcePlans(query), enabled, placeholderData: previous => previous }); };
export const useBudgetSourcePlan = (planId: number | null, enabled = true) => { const useCases = useWorkforceBudgetUseCases(); return useQuery({ queryKey: workforceBudgetKeys.sourcePlan(planId ?? 0), queryFn: () => useCases.getSourcePlanById(planId!), enabled: enabled && !!planId }); };
export const usePositionEnvelopes = (query: PositionEnvelopePageQuery) => { const useCases = usePositionEnvelopeUseCases(); return useQuery({ queryKey: positionEnvelopeKeys.list(query), queryFn: () => useCases.getPage(query), placeholderData: previous => previous }); };
export const usePositionEnvelope = (id: number | null, enabled = true) => { const useCases = usePositionEnvelopeUseCases(); return useQuery({ queryKey: positionEnvelopeKeys.detail(id ?? 0), queryFn: () => useCases.getById(id!), enabled: enabled && !!id }); };
function useBudgetMutation<T, TResult>(mutationFn: (value: T) => Promise<TResult>) { const client = useQueryClient(); return useMutation({ mutationFn, onSuccess: async () => client.invalidateQueries({ queryKey: workforceBudgetKeys.all }) }); }
function useApprovalMutation<T, TResult>(mutationFn: (value: T) => Promise<TResult>) { const client = useQueryClient(); return useMutation({ mutationFn, onSuccess: async () => { await client.invalidateQueries({ queryKey: workforceBudgetKeys.all }); await client.invalidateQueries({ queryKey: positionEnvelopeKeys.all }); await client.invalidateQueries({ queryKey: workforcePlanKeys.all }); } }); }
export const useCreateWorkforceBudget = () => { const useCases = useWorkforceBudgetUseCases(); return useBudgetMutation((request: WorkforceBudgetRequest) => useCases.create(request)); };
export const useUpdateWorkforceBudget = () => { const useCases = useWorkforceBudgetUseCases(); return useBudgetMutation(({ id, request }: { id: number; request: UpdateWorkforceBudgetRequest }) => useCases.update(id, request)); };
export const useSubmitWorkforceBudget = () => { const useCases = useWorkforceBudgetUseCases(); return useBudgetMutation((action: WorkforceBudgetAction) => useCases.submit(action)); };
export const useApproveWorkforceBudget = () => { const useCases = useWorkforceBudgetUseCases(); return useApprovalMutation((action: WorkforceBudgetAction) => useCases.approve(action)); };
export const useRejectWorkforceBudget = () => { const useCases = useWorkforceBudgetUseCases(); return useBudgetMutation((action: RejectWorkforceBudgetAction) => useCases.reject(action)); };
