import { useMemo, useState } from 'react';
import { StyleSheet, View } from 'react-native';
import { useQueryClient } from '@tanstack/react-query';
import { useTranslation } from 'react-i18next';
import { permissions, useAuthorization } from '@/src/features/auth';
import { AppCard, AppSpreadsheetImportView, AppStatusBadge, AppText, type AppAlertSeverity, type SpreadsheetImportPhase } from '@/src/shared/components';
import { useAppReadOnly } from '@/src/shared/contexts/AppReadOnlyContext';
import { useAppTheme } from '@/src/core/theme';
import { isAmbiguousImportError, pickNativeSpreadsheet, shareSpreadsheetTemplate, spreadsheetErrorMessage, type NativeSpreadsheetFile } from '@/src/shared/importing';
import { addressTypeKeys } from '../../queries/address-type-keys';
import { useBulkCreateAddressTypes } from '../../queries/use-address-types';
import { ADDRESS_TYPE_IMPORT_HEADERS, ADDRESS_TYPE_IMPORT_MAX_BYTES, ADDRESS_TYPE_IMPORT_MAX_ROWS, ADDRESS_TYPE_IMPORT_TEMPLATE_FILE, parseAddressTypeImport, type AddressTypeImportRow } from './address-type-import';

export function AddressTypeImportView() {
  const { t } = useTranslation(); const { theme } = useAppTheme(); const client = useQueryClient(); const { isReadOnly, notifyBlockedAction } = useAppReadOnly(); const { allowed } = useAuthorization({ requiredPermissions: [permissions.CreateAddressTypes] }); const mutation = useBulkCreateAddressTypes();
  const [file, setFile] = useState<NativeSpreadsheetFile | null>(null); const [rows, setRows] = useState<AddressTypeImportRow[]>([]); const [phase, setPhase] = useState<SpreadsheetImportPhase>('idle'); const [feedback, setFeedback] = useState<{ severity: AppAlertSeverity; message: string } | null>(null);
  const counts = useMemo(() => ({ total: rows.length, ready: rows.filter((row) => row.status === 'ready').length, invalid: rows.filter((row) => row.status === 'invalid').length, uploaded: rows.filter((row) => row.status === 'uploaded').length }), [rows]);
  const guard = () => { if (isReadOnly) { notifyBlockedAction(); return false; } if (!allowed) { setFeedback({ severity: 'error', message: t('spreadsheetImport.permissionDenied') }); return false; } return true; };
  const pick = async () => { if (!guard()) return; try { const selected = await pickNativeSpreadsheet(); if (!selected) return; setPhase('parsing'); setFeedback(null); const parsed = await parseAddressTypeImport(selected, t); setFile(selected); setRows(parsed); setPhase('preview'); const invalid = parsed.filter((row) => row.status === 'invalid').length; setFeedback({ severity: invalid ? 'warning' : 'success', message: t(invalid ? 'spreadsheetImport.previewWithErrors' : 'spreadsheetImport.previewReady', { count: parsed.length, invalid }) }); } catch (error) { setPhase('failed'); setFeedback({ severity: 'error', message: spreadsheetErrorMessage(error, t) }); } };
  const submit = async () => { if (!guard()) return; const pending = rows.filter((row): row is AddressTypeImportRow & { request: NonNullable<AddressTypeImportRow['request']> } => row.status === 'ready' && row.request !== null); if (!pending.length) return; setPhase('submitting'); setFeedback(null); try { const result = await mutation.mutateAsync(pending.map((row) => row.request)); const submitted = new Set(pending.map((row) => row.rowNumber)); setRows((current) => current.map((row) => submitted.has(row.rowNumber) ? { ...row, status: 'uploaded', error: undefined } : row)); setPhase('succeeded'); setFeedback({ severity: 'success', message: t('addressTypes.import.succeeded', { count: result.createdCount }) }); } catch (error) { const uncertain = isAmbiguousImportError(error); const submitted = new Set(pending.map((row) => row.rowNumber)); setRows((current) => current.map((row) => submitted.has(row.rowNumber) ? { ...row, status: uncertain ? 'uncertain' : 'failed' } : row)); setPhase(uncertain ? 'uncertain' : 'failed'); setFeedback({ severity: uncertain ? 'warning' : 'error', message: uncertain ? t('spreadsheetImport.uncertain') : spreadsheetErrorMessage(error, t) }); } };
  const reconcile = async () => { await client.invalidateQueries({ queryKey: addressTypeKeys.all }); setFeedback({ severity: 'info', message: t('spreadsheetImport.reconciled') }); };
  return <AppSpreadsheetImportView counts={counts} feedback={feedback} file={file} headers={ADDRESS_TYPE_IMPORT_HEADERS} maxBytes={ADDRESS_TYPE_IMPORT_MAX_BYTES} maxRows={ADDRESS_TYPE_IMPORT_MAX_ROWS} onClear={() => { setFile(null); setRows([]); setPhase('idle'); setFeedback(null); }} onPick={() => void pick()} onReconcile={() => void reconcile()} onShareTemplate={() => void shareSpreadsheetTemplate(ADDRESS_TYPE_IMPORT_HEADERS, ADDRESS_TYPE_IMPORT_TEMPLATE_FILE)} onSubmit={() => void submit()} phase={phase} submitDisabled={!allowed || isReadOnly}>{rows.length ? <View style={styles.rows}>{rows.map((row) => <AppCard key={row.rowNumber} padding="sm" style={styles.row}><View style={styles.rowHeader}><AppText variant="label">{t('spreadsheetImport.row', { number: row.rowNumber })}</AppText><AppStatusBadge color={row.status === 'uploaded' ? theme.colors.success : row.status === 'invalid' || row.status === 'failed' ? theme.colors.danger : row.status === 'uncertain' ? theme.colors.warning : theme.colors.primary} label={t(`spreadsheetImport.status.${row.status}`)} /></View><AppText numberOfLines={1} variant="bodySmall">{row.values.nameEn} · {row.values.nameAr}</AppText>{row.error ? <AppText color="danger" variant="caption">{row.error}</AppText> : null}</AppCard>)}</View> : null}</AppSpreadsheetImportView>;
}
const styles = StyleSheet.create({ rows: { gap: 6 }, row: { gap: 3 }, rowHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8 } });
