import type {
  RecruitmentStageConfig,
  RejectionReasonConfig,
  RecruitmentSourceConfig,
  EvaluationCriterionConfig,
  RecruitmentGeneralSettings,
  RecruitmentSettingsDto,
} from '../types';

export const DEFAULT_STAGES: RecruitmentStageConfig[] = [
  {
    id: 'stage_applied',
    nameAr: 'تم التقديم',
    nameEn: 'Applied',
    sequence: 10,
    color: '#1976d2',
    foldedInKanban: false,
    isDefault: true,
    sendEmailNotification: true,
  },
  {
    id: 'stage_screening',
    nameAr: 'قيد الفرز الأولي',
    nameEn: 'Screening',
    sequence: 20,
    color: '#ed6c02',
    foldedInKanban: false,
    isDefault: false,
    sendEmailNotification: false,
  },
  {
    id: 'stage_shortlist',
    nameAr: 'القائمة المختصرة',
    nameEn: 'Shortlisted',
    sequence: 30,
    color: '#9c27b0',
    foldedInKanban: false,
    isDefault: false,
    sendEmailNotification: true,
  },
  {
    id: 'stage_tech_interview',
    nameAr: 'المقابلة الفنية',
    nameEn: 'Technical Interview',
    sequence: 40,
    color: '#0288d1',
    foldedInKanban: false,
    isDefault: false,
    sendEmailNotification: true,
  },
  {
    id: 'stage_hr_interview',
    nameAr: 'مقابلة الإدارة والموارد البشرية',
    nameEn: 'HR & Culture Fit',
    sequence: 50,
    color: '#5c6bc0',
    foldedInKanban: false,
    isDefault: false,
    sendEmailNotification: true,
  },
  {
    id: 'stage_offer_issued',
    nameAr: 'تم إرسال العرض الوظيفي',
    nameEn: 'Offer Issued',
    sequence: 60,
    color: '#ff9800',
    foldedInKanban: false,
    isDefault: false,
    sendEmailNotification: true,
  },
  {
    id: 'stage_offer_accepted',
    nameAr: 'تم قبول العرض',
    nameEn: 'Offer Accepted',
    sequence: 70,
    color: '#009688',
    foldedInKanban: false,
    isDefault: false,
    sendEmailNotification: false,
  },
  {
    id: 'stage_hired',
    nameAr: 'تم التعيين الرسمي',
    nameEn: 'Hired',
    sequence: 80,
    color: '#2e7d32',
    foldedInKanban: true,
    isDefault: false,
    sendEmailNotification: true,
  },
];

export const DEFAULT_REASONS: RejectionReasonConfig[] = [
  {
    id: 'rr_salary',
    reasonAr: 'الراتب المتوقع أعلى من الميزانية المحددة للوظيفة',
    reasonEn: 'Expected salary exceeds budgeted compensation range',
    category: 'salary',
    sendAutoEmail: true,
  },
  {
    id: 'rr_tech_fail',
    reasonAr: 'عدم اجتياز التقييم الفني أو العملي',
    reasonEn: 'Did not pass technical assessment or practical evaluation',
    category: 'qualifications',
    sendAutoEmail: true,
  },
  {
    id: 'rr_insufficient_exp',
    reasonAr: 'عدم تطابق سنوات الخبرة أو المؤهلات التخصصية المطلوبة',
    reasonEn: 'Insufficient years of relevant experience or required qualifications',
    category: 'qualifications',
    sendAutoEmail: true,
  },
  {
    id: 'rr_no_show',
    reasonAr: 'عدم حضور المقابلة المحددة بدون اعتذار مسبق',
    reasonEn: 'Candidate did not attend scheduled interview without prior notice',
    category: 'other',
    sendAutoEmail: false,
  },
  {
    id: 'rr_withdrew',
    reasonAr: 'اعتذار المرشح لظروف شخصية أو قبوله عرضاً آخر',
    reasonEn: 'Candidate withdrew application or accepted another offer',
    category: 'candidate_withdrew',
    sendAutoEmail: false,
  },
  {
    id: 'rr_culture_fit',
    reasonAr: 'عدم التوافق مع قيم وثقافة بيئة العمل',
    reasonEn: 'Culture and behavioral alignment mismatch',
    category: 'behavioral',
    sendAutoEmail: true,
  },
];

export const DEFAULT_SOURCES: RecruitmentSourceConfig[] = [
  {
    id: 'src_linkedin',
    nameAr: 'لينكد إن',
    nameEn: 'LinkedIn',
    type: 'social',
    isActive: true,
    applicationsCount: 54,
    hiredCount: 7,
  },
  {
    id: 'src_portal',
    nameAr: 'بوابة التوظيف الرسمية',
    nameEn: 'Company Careers Portal',
    type: 'portal',
    isActive: true,
    applicationsCount: 96,
    hiredCount: 15,
  },
  {
    id: 'src_referral',
    nameAr: 'ترشيح من موظف داخلي',
    nameEn: 'Employee Referral',
    type: 'referral',
    isActive: true,
    applicationsCount: 22,
    hiredCount: 6,
  },
  {
    id: 'src_wuzzuf',
    nameAr: 'منصات التوظيف (Wuzzuf / Bayt)',
    nameEn: 'Recruitment Platforms (Wuzzuf / Bayt)',
    type: 'portal',
    isActive: true,
    applicationsCount: 68,
    hiredCount: 9,
  },
  {
    id: 'src_agency',
    nameAr: 'وكالات ومكاتب التوظيف الخارجية',
    nameEn: 'Recruitment Agencies & Headhunters',
    type: 'agency',
    isActive: true,
    applicationsCount: 14,
    hiredCount: 4,
  },
  {
    id: 'src_fairs',
    nameAr: 'معارض التوظيف والجامعات',
    nameEn: 'Job Fairs & Universities',
    type: 'fair',
    isActive: false,
    applicationsCount: 28,
    hiredCount: 2,
  },
];

export const DEFAULT_CRITERIA: EvaluationCriterionConfig[] = [
  {
    id: 'crit_tech',
    titleAr: 'الكفاءة والخبرة الفنية التخصصية',
    titleEn: 'Technical Competence & Core Expertise',
    category: 'technical',
    maxScore: 5,
    weight: 30,
    isMandatory: true,
  },
  {
    id: 'crit_comm',
    titleAr: 'مهارات التواصل والعرض والتعبير',
    titleEn: 'Communication & Presentation Skills',
    category: 'communication',
    maxScore: 5,
    weight: 20,
    isMandatory: true,
  },
  {
    id: 'crit_problem_solving',
    titleAr: 'حل المشكلات والتفكير التحليلي',
    titleEn: 'Problem Solving & Analytical Thinking',
    category: 'problem_solving',
    maxScore: 5,
    weight: 25,
    isMandatory: true,
  },
  {
    id: 'crit_culture',
    titleAr: 'التوافق مع ثقافة وقيم الشركة',
    titleEn: 'Culture & Values Alignment',
    category: 'culture',
    maxScore: 5,
    weight: 15,
    isMandatory: true,
  },
  {
    id: 'crit_leadership',
    titleAr: 'العمل الجماعي والروح القيادية',
    titleEn: 'Teamwork & Leadership Qualities',
    category: 'leadership',
    maxScore: 5,
    weight: 10,
    isMandatory: false,
  },
];

export const DEFAULT_GENERAL_SETTINGS: RecruitmentGeneralSettings = {
  defaultCurrency: 'EGP',
  offerExpiryDays: 7,
  autoPublishOpening: true,
  enforceHeadcountCapacity: true,
  defaultProbationMonths: 3,
  enablePublicPortal: true,
  inboundEmailAlias: 'careers@company.com',
};

export const DEFAULT_RECRUITMENT_SETTINGS: RecruitmentSettingsDto = {
  stages: DEFAULT_STAGES,
  rejectionReasons: DEFAULT_REASONS,
  sources: DEFAULT_SOURCES,
  evaluationCriteria: DEFAULT_CRITERIA,
  general: DEFAULT_GENERAL_SETTINGS,
};
