import { useCallback, useMemo, useState } from 'react';
import { RefreshControl, StyleSheet, View } from 'react-native';
import { useTranslation } from 'react-i18next';
import { ApiError } from '@/src/core/api';
import { useAppTheme } from '@/src/core/theme';
import { permissions, useAuthorization } from '@/src/features/auth';
import { useAppReadOnly } from '@/src/shared/contexts/AppReadOnlyContext';
import { toApiPageNumber, useServerListState } from '@/src/shared/listing';
import { AppDataCard, AppDataTable, type AppDataTableColumn, AppIconButton, AppListScreen, AppScreen, AppStateView, AppStatusBadge, AppText, ConfirmationDialog, showToast } from '@/src/shared/components';
import { FiscalYearFilterButton } from '../components/FiscalYearFilterButton';
import { FiscalYearForm } from '../components/FiscalYearForm';
import { useArchiveFiscalYear, useFiscalYear, useFiscalYearLifecycle, useFiscalYears, useRestoreFiscalYear, useSaveFiscalYear } from '../queries/use-fiscal-years';
import type { FiscalYear, FiscalYearFilters, FiscalYearLifecycleAction, FiscalYearRequest, FiscalYearSearchField, FiscalYearSearchOperator, FiscalYearSortColumn } from '../types/fiscal-year';

type FormMode = 'create' | 'edit' | 'view';
type Pending = { kind: 'archive' | 'restore' | 'lifecycle'; item: FiscalYear; action?: FiscalYearLifecycleAction } | null;
const initialFilters: FiscalYearFilters = { recordStatus: 'active', lifecycleStatus: 'all' };

export function FiscalYearsScreen() {
  const { t } = useTranslation(); const { theme } = useAppTheme(); const { isReadOnly, notifyBlockedAction } = useAppReadOnly();
  const { allowed: createAllowed } = useAuthorization({ requiredPermissions: [permissions.CreateFiscalYears] });
  const { allowed: editAllowed } = useAuthorization({ requiredPermissions: [permissions.EditFiscalYears] });
  const { allowed: deleteAllowed } = useAuthorization({ requiredPermissions: [permissions.DeleteFiscalYears] });
  const { allowed: lifecycleAllowed } = useAuthorization({ requiredPermissions: [permissions.ManageFiscalYearLifecycle] });
  const canCreate = createAllowed && !isReadOnly; const canEdit = editAllowed && !isReadOnly; const canDelete = deleteAllowed && !isReadOnly; const canLifecycle = lifecycleAllowed && !isReadOnly;
  const list = useServerListState<FiscalYearSortColumn, FiscalYearFilters>({ initialFilters, initialPageSize: 5, initialSort: { columnId: 'startDate', direction: 'descending' } });
  const [searchField, setSearchField] = useState<FiscalYearSearchField>('all'); const [searchOperator, setSearchOperator] = useState<FiscalYearSearchOperator>('contains');
  const query = useFiscalYears({ pageNumber: toApiPageNumber(list.state.page), pageSize: list.state.pageSize, search: list.state.search, searchField, searchOperator, recordStatus: list.state.filters.recordStatus, lifecycleStatus: list.state.filters.lifecycleStatus, sortBy: list.state.sort?.columnId ?? 'startDate', sortDirection: list.state.sort?.direction === 'ascending' ? 'asc' : 'desc' });
  const [formOpen, setFormOpen] = useState(false); const [formMode, setFormMode] = useState<FormMode>('view'); const [selected, setSelected] = useState<FiscalYear | null>(null); const [pending, setPending] = useState<Pending>(null);
  const details = useFiscalYear(selected?.id ?? null, formOpen && formMode !== 'create');
  const saveMutation = useSaveFiscalYear(); const archiveMutation = useArchiveFiscalYear(); const restoreMutation = useRestoreFiscalYear(); const lifecycleMutation = useFiscalYearLifecycle();
  const rows = query.data?.items ?? [];
  const formItem = details.data ?? (selected ? { ...selected, periods: [] } : null);
  const statusKey = (value: number) => ['', 'draft', 'open', 'closing', 'closed', 'locked'][value];
  const openForm = useCallback((mode: FormMode, item: FiscalYear | null) => { if (mode !== 'view' && isReadOnly) return notifyBlockedAction(); setSelected(item); setFormMode(mode); setFormOpen(true); }, [isReadOnly, notifyBlockedAction]);
  const closeForm = useCallback(() => { setFormOpen(false); setSelected(null); }, []);
  const save = useCallback(async (request: FiscalYearRequest) => { try { await saveMutation.mutateAsync({ id: formMode === 'edit' ? selected?.id ?? null : null, request, rowVersion: details.data?.rowVersion ?? selected?.rowVersion }); showToast.success(t(formMode === 'edit' ? 'fiscalYears.messages.updated' : 'fiscalYears.messages.created')); closeForm(); } catch (error) { showToast.error(error, t('fiscalYears.messages.saveFailed')); } }, [closeForm, details.data, formMode, saveMutation, selected, t]);
  const nextLifecycle = (item: FiscalYear): FiscalYearLifecycleAction | null => ({ 1: 'open', 2: 'beginClosing', 3: 'close', 4: 'lock' } as const)[item.status as 1 | 2 | 3 | 4] ?? null;
  const confirm = useCallback(async () => { if (!pending) return; if (isReadOnly) return notifyBlockedAction(); try { if (pending.kind === 'archive') await archiveMutation.mutateAsync(pending.item.id); else if (pending.kind === 'restore') await restoreMutation.mutateAsync({ id: pending.item.id, rowVersion: pending.item.rowVersion }); else if (pending.action) await lifecycleMutation.mutateAsync({ id: pending.item.id, rowVersion: pending.item.rowVersion, action: pending.action }); showToast.success(t(`fiscalYears.messages.${pending.kind}`)); setPending(null); } catch (error) { showToast.error(error, t('fiscalYears.messages.actionFailed')); } }, [archiveMutation, isReadOnly, lifecycleMutation, notifyBlockedAction, pending, restoreMutation, t]);
  const columns = useMemo<AppDataTableColumn<FiscalYear>[]>(() => [
    { id: 'code', header: t('fiscalYears.fields.code'), width: 120, sortable: true, render: item => <AppText variant="bodySmall" weight="700">{item.code}</AppText> },
    { id: 'nameEn', header: t('fiscalYears.fields.nameEn'), width: 170, sortable: true, render: item => <AppText variant="bodySmall">{item.nameEn}</AppText> },
    { id: 'nameAr', header: t('fiscalYears.fields.nameAr'), width: 170, sortable: true, render: item => <AppText variant="bodySmall">{item.nameAr}</AppText> },
    { id: 'startDate', header: t('fiscalYears.fields.startDate'), width: 125, sortable: true, render: item => <AppText variant="bodySmall">{item.startDate}</AppText> },
    { id: 'endDate', header: t('fiscalYears.fields.endDate'), width: 125, sortable: true, render: item => <AppText variant="bodySmall">{item.endDate}</AppText> },
    { id: 'status', header: t('fiscalYears.fields.status'), width: 120, sortable: true, render: item => <AppStatusBadge color={item.status === 2 ? theme.colors.success : item.status === 3 ? theme.colors.warning : theme.colors.primary} label={t(`fiscalYears.status.${statusKey(item.status)}`)} /> },
    { id: 'actions', header: t('common.actions'), width: 190, align: 'center', render: item => <View style={styles.actions}><AppIconButton icon="eye-outline" label={t('common.view')} onPress={() => openForm('view', item)} />{canEdit && !item.isDeleted && item.status === 1 ? <AppIconButton icon="create-outline" label={t('common.edit')} onPress={() => openForm('edit', item)} /> : null}{canLifecycle && !item.isDeleted && item.status < 5 ? <AppIconButton icon="arrow-forward-circle-outline" label={t('fiscalYears.actions.lifecycle')} onPress={() => { const action = nextLifecycle(item); if (action) setPending({ kind: 'lifecycle', item, action }); }} /> : null}{canDelete ? <AppIconButton icon={item.isDeleted ? 'refresh-outline' : 'archive-outline'} label={t(item.isDeleted ? 'common.restore' : 'common.archive')} onPress={() => setPending({ kind: item.isDeleted ? 'restore' : 'archive', item })} /> : null}</View> },
  ], [canDelete, canEdit, canLifecycle, openForm, t, theme.colors.primary, theme.colors.success, theme.colors.warning]);
  if (query.isLoading) return <AppScreen edges={['left', 'right', 'bottom']}><AppStateView state="loading" /></AppScreen>;
  if (query.error) return <AppScreen edges={['left', 'right', 'bottom']}><AppStateView state="error" message={errorMessage(query.error, t('fiscalYears.messages.loadFailed'))} onRetry={() => void query.refetch()} /></AppScreen>;
  const filterValues = { field: searchField, operator: searchOperator, ...list.state.filters };
  return <AppScreen edges={['left', 'right', 'bottom']} contentContainerStyle={styles.screen} refreshControl={<RefreshControl refreshing={query.isRefetching} onRefresh={() => void query.refetch()} tintColor={theme.colors.primary} colors={[theme.colors.primary]} />}>
    <AppListScreen<FiscalYear, 'table' | 'cards'> defaultView="table" items={rows} isFetching={query.isFetching} emptyContent={<AppStateView state="empty" message={t('fiscalYears.empty')} />} fillViewSelector showViewLabels showResultCount={false} searchValue={list.searchInput} searchPlaceholder={t('fiscalYears.search.placeholder')} onSearchChange={list.setSearchInput}
      filterControl={<FiscalYearFilterButton values={filterValues} onApply={values => { setSearchField(values.field); setSearchOperator(values.operator); list.setFilters({ recordStatus: values.recordStatus, lifecycleStatus: values.lifecycleStatus }); list.setPage(0); }} />}
      searchActions={canCreate ? <AppIconButton icon="add-outline" label={t('fiscalYears.actions.add')} color={theme.colors.onPrimary} onPress={() => openForm('create', null)} size={22} style={({ pressed }) => ({ backgroundColor: theme.colors.primary, opacity: pressed ? .75 : 1 })} /> : null}
      serverPagination={{ page: list.state.page, pageSize: list.state.pageSize, totalItems: query.data?.metaData.totalCount ?? 0, pageSizeOptions: [3, 5, 10], onPageChange: list.setPage, onPageSizeChange: list.setPageSize }}
      views={[
        { value: 'table', icon: 'grid-outline', label: t('multiView.table'), defaultPageSize: 5, render: items => <AppDataTable rows={items} columns={columns} getRowKey={item => item.id} showPagination={false} serverState={{ page: list.state.page, pageSize: list.state.pageSize, totalRows: query.data?.metaData.totalCount ?? 0, sort: list.state.sort, onPageChange: list.setPage, onPageSizeChange: list.setPageSize, onSortChange: sort => list.setSort(sort ? { ...sort, columnId: sort.columnId as FiscalYearSortColumn } : null) }} /> },
        { value: 'cards', icon: 'albums-outline', label: t('multiView.cards'), defaultPageSize: 3, scrollable: true, render: items => <View style={styles.cards}>{items.map((item, index) => <AppDataCard key={item.id} active={index === 0} padding="md"><View style={styles.cardHeader}><View style={styles.cardTitle}><AppText variant="titleSmall" weight="800">{item.nameEn}</AppText><AppText color="muted" variant="caption">{item.nameAr} • {item.code}</AppText></View><AppStatusBadge color={item.status === 2 ? theme.colors.success : theme.colors.primary} label={t(`fiscalYears.status.${statusKey(item.status)}`)} /></View><AppText variant="bodySmall">{item.startDate} — {item.endDate}</AppText><AppText color="muted" variant="caption">{t('fiscalYears.periods.count', { count: item.periodsCount })} • {t(item.periodFrequency === 1 ? 'fiscalYears.frequency.monthly' : 'fiscalYears.frequency.quarterly')}</AppText><View style={styles.actions}><AppIconButton icon="eye-outline" label={t('common.view')} onPress={() => openForm('view', item)} />{canEdit && !item.isDeleted && item.status === 1 ? <AppIconButton icon="create-outline" label={t('common.edit')} onPress={() => openForm('edit', item)} /> : null}{canLifecycle && !item.isDeleted && item.status < 5 ? <AppIconButton icon="arrow-forward-circle-outline" label={t('fiscalYears.actions.lifecycle')} onPress={() => { const action = nextLifecycle(item); if (action) setPending({ kind: 'lifecycle', item, action }); }} /> : null}{canDelete ? <AppIconButton icon={item.isDeleted ? 'refresh-outline' : 'archive-outline'} label={t(item.isDeleted ? 'common.restore' : 'common.archive')} onPress={() => setPending({ kind: item.isDeleted ? 'restore' : 'archive', item })} /> : null}</View></AppDataCard>)}</View> },
      ]} />
    {formOpen ? <FiscalYearForm key={`${formMode}-${selected?.id ?? 'new'}-${details.data?.rowVersion ?? 'pending'}`} item={formItem} mode={formMode} loading={saveMutation.isPending} detailLoading={formMode !== 'create' && details.isFetching} detailError={details.error ? errorMessage(details.error, t('fiscalYears.messages.loadFailed')) : null} onRetryDetail={() => void details.refetch()} onClose={closeForm} onSave={save} /> : null}
    <ConfirmationDialog visible={pending !== null} title={t(`fiscalYears.confirm.${pending?.kind === 'lifecycle' ? pending.action : pending?.kind ?? 'archive'}Title`)} description={t(`fiscalYears.confirm.${pending?.kind === 'lifecycle' ? pending.action : pending?.kind ?? 'archive'}Description`)} confirmLabel={t(pending?.kind === 'restore' ? 'common.restore' : pending?.kind === 'archive' ? 'common.archive' : `fiscalYears.lifecycle.${pending?.action ?? 'open'}`)} tone={pending?.kind === 'archive' ? 'warning' : 'default'} loading={archiveMutation.isPending || restoreMutation.isPending || lifecycleMutation.isPending} onCancel={() => setPending(null)} onConfirm={() => void confirm()} />
  </AppScreen>;
}
function errorMessage(error: unknown, fallback: string) { return error instanceof ApiError || error instanceof Error ? error.message || fallback : fallback; }
const styles = StyleSheet.create({ screen: { gap: 12, paddingVertical: 8 }, actions: { flexDirection: 'row', justifyContent: 'center', gap: 4, flexWrap: 'wrap' }, cards: { gap: 8 }, cardHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', gap: 8 }, cardTitle: { flex: 1, gap: 2 } });
