import { useCallback, useMemo, useState } from 'react';
import { RefreshControl, StyleSheet, View } from 'react-native';
import { useTranslation } from 'react-i18next';
import { ApiError } from '@/src/core/api';
import { useAppTheme } from '@/src/core/theme';
import { permissions, useAuthorization } from '@/src/features/auth';
import { useAppReadOnly } from '@/src/shared/contexts/AppReadOnlyContext';
import { toApiPageNumber, useServerListState } from '@/src/shared/listing';
import { AppButton, AppDataTable, type AppDataTableColumn, AppIconButton, AppListScreen, AppScreen, AppStateView, AppStatusBadge, AppText, ConfirmationDialog, showToast } from '@/src/shared/components';
import { AddressTypeCard } from '../components/AddressTypeCard';
import { AddressTypeFilterButton } from '../components/AddressTypeFilterButton';
import { AddressTypeForm } from '../components/AddressTypeForm';
import { AddressTypeReportView } from '../components/AddressTypeReportView';
import { AddressTypesChartView } from '../components/AddressTypesChartView';
import { AddressTypeImportView } from '../components/import-data/AddressTypeImportView';
import { useAddressTypes, useArchiveAddressType, useBulkArchiveAddressTypes, useRestoreAddressType, useSaveAddressType } from '../queries/use-address-types';
import type { AddressType, AddressTypeFilters, AddressTypeRequest, AddressTypeSearchField, AddressTypeSearchOperator, AddressTypeSortColumn } from '../types/address-type';

type FormMode = 'create' | 'edit' | 'view'; type PendingAction = { kind: 'archive'; value: AddressType } | { kind: 'bulk' } | null; const initialFilters: AddressTypeFilters = { status: 'active' };
export function AddressTypesScreen() {
  const { i18n, t } = useTranslation(); const { theme } = useAppTheme(); const { isReadOnly, notifyBlockedAction } = useAppReadOnly(); const { allowed: createAllowed } = useAuthorization({ requiredPermissions: [permissions.CreateAddressTypes] }); const { allowed: editAllowed } = useAuthorization({ requiredPermissions: [permissions.EditAddressTypes] }); const { allowed: deleteAllowed } = useAuthorization({ requiredPermissions: [permissions.DeleteAddressTypes] }); const { allowed: reportAllowed } = useAuthorization({ requiredPermissions: [permissions.ViewCrystalReports] });
  const canCreate = createAllowed && !isReadOnly; const canEdit = editAllowed && !isReadOnly; const canDelete = deleteAllowed && !isReadOnly; const list = useServerListState<AddressTypeSortColumn, AddressTypeFilters>({ initialFilters, initialPageSize: 5, initialSort: { columnId: 'createdOn', direction: 'descending' } }); const [field, setField] = useState<AddressTypeSearchField>('all'); const [operator, setOperator] = useState<AddressTypeSearchOperator>('contains');
  const query = useAddressTypes({ pageNumber: toApiPageNumber(list.state.page), pageSize: list.state.pageSize, search: list.state.search, searchField: field, searchOperator: operator, status: list.state.filters.status, sortBy: list.state.sort?.columnId ?? 'nameEn', sortDirection: list.state.sort?.direction === 'descending' ? 'desc' : 'asc' }); const saveMutation = useSaveAddressType(); const archiveMutation = useArchiveAddressType(); const restoreMutation = useRestoreAddressType(); const bulkMutation = useBulkArchiveAddressTypes(); const rows = query.data?.items ?? [];
  const [formMode, setFormMode] = useState<FormMode>('view'); const [selected, setSelected] = useState<AddressType | null>(null); const [pending, setPending] = useState<PendingAction>(null); const [selectedIds, setSelectedIds] = useState<number[]>([]);
  const clearSelection = useCallback(() => { setSelectedIds([]); setPending((current) => current?.kind === 'bulk' ? null : current); }, []); const changeSearch = useCallback((value: string) => { clearSelection(); list.setSearchInput(value); }, [clearSelection, list]); const changePage = useCallback((value: number) => { clearSelection(); list.setPage(value); }, [clearSelection, list]); const changePageSize = useCallback((value: number) => { clearSelection(); list.setPageSize(value); }, [clearSelection, list]); const applyFilters = useCallback((next: { field: AddressTypeSearchField; operator: AddressTypeSearchOperator; status: AddressTypeFilters['status'] }) => { clearSelection(); setField(next.field); setOperator(next.operator); list.setFilters({ status: next.status }); list.setPage(0); }, [clearSelection, list]); const changeSort = useCallback((sort: { columnId: string; direction: 'ascending' | 'descending' } | null) => { clearSelection(); list.setSort(sort ? { columnId: sort.columnId as AddressTypeSortColumn, direction: sort.direction } : null); }, [clearSelection, list]);
  const openForm = useCallback((mode: FormMode, value: AddressType | null) => { if (mode !== 'view' && isReadOnly) { notifyBlockedAction(); return; } setFormMode(mode); setSelected(value); }, [isReadOnly, notifyBlockedAction]); const closeForm = useCallback(() => { setSelected(null); setFormMode('view'); }, []); const toggle = useCallback((value: AddressType) => setSelectedIds((ids) => ids.includes(value.id) ? ids.filter((id) => id !== value.id) : ids.length >= 100 ? ids : [...ids, value.id]), []);
  const save = useCallback(async (request: AddressTypeRequest) => { if (isReadOnly) { notifyBlockedAction(); return; } if (formMode === 'edit' ? !editAllowed : !createAllowed) return; try { await saveMutation.mutateAsync({ id: formMode === 'edit' ? selected?.id ?? null : null, request }); closeForm(); showToast.success(t('addressTypes.saved')); } catch (error) { showToast.error(error, t('addressTypes.saveFailed')); } }, [closeForm, createAllowed, editAllowed, formMode, isReadOnly, notifyBlockedAction, saveMutation, selected?.id, t]);
  const restore = useCallback(async (value: AddressType) => { if (isReadOnly) { notifyBlockedAction(); return; } if (!deleteAllowed) return; try { await restoreMutation.mutateAsync(value.id); showToast.success(t('addressTypes.restored')); } catch (error) { showToast.error(error, t('addressTypes.restoreFailed')); } }, [deleteAllowed, isReadOnly, notifyBlockedAction, restoreMutation, t]);
  const confirm = useCallback(async () => { if (!pending) return; if (isReadOnly) { notifyBlockedAction(); return; } if (!deleteAllowed) return; try { if (pending.kind === 'bulk') { const result = await bulkMutation.mutateAsync(selectedIds); setSelectedIds([]); showToast.success(t('addressTypes.bulkArchived', { count: result.archivedCount })); } else { await archiveMutation.mutateAsync(pending.value.id); setSelectedIds((ids) => ids.filter((id) => id !== pending.value.id)); showToast.success(t('addressTypes.archivedSuccess')); } setPending(null); } catch (error) { showToast.error(error, t('addressTypes.archiveFailed')); } }, [archiveMutation, bulkMutation, deleteAllowed, isReadOnly, notifyBlockedAction, pending, selectedIds, t]);
  const columns = useMemo<AppDataTableColumn<AddressType>[]>(() => [
    { id: 'nameEn', header: t('addressTypes.nameEn'), width: 160, sortable: true, render: (item) => <AppText variant="bodySmall" weight="700">{item.nameEn}</AppText> },
    { id: 'nameAr', header: t('addressTypes.nameAr'), width: 160, sortable: true, render: (item) => <AppText variant="bodySmall">{item.nameAr}</AppText> },
    { id: 'addresses', header: t('addressTypes.addresses'), width: 88, align: 'center', render: (item) => <AppText variant="bodySmall">{item.addressesCount}</AppText> },
    { id: 'createdOn', header: t('addressTypes.createdOn'), width: 128, sortable: true, render: (item) => <AppText variant="bodySmall">{formatDate(item.createdOn, i18n.language)}</AppText> },
    { id: 'status', header: t('addressTypes.status'), width: 104, align: 'center', render: (item) => <AppStatusBadge color={item.isDeleted ? theme.colors.warning : theme.colors.success} label={t(item.isDeleted ? 'addressTypes.archived' : 'addressTypes.active')} /> },
    { id: 'actions', header: t('addressTypes.actions'), width: 184, align: 'center', render: (item) => <View style={styles.actions}><AppIconButton icon="eye-outline" label={t('addressTypes.viewAddressType')} onPress={() => openForm('view', item)} />{canEdit && !item.isDeleted ? <AppIconButton icon="create-outline" label={t('addressTypes.editAddressType')} onPress={() => openForm('edit', item)} /> : null}{canDelete ? <AppIconButton icon={item.isDeleted ? 'refresh-outline' : 'archive-outline'} label={t(item.isDeleted ? 'addressTypes.restore' : 'addressTypes.archive')} onPress={() => item.isDeleted ? void restore(item) : setPending({ kind: 'archive', value: item })} /> : null}</View> },
  ], [canDelete, canEdit, i18n.language, openForm, restore, t, theme.colors.success, theme.colors.warning]);
  if (query.isLoading) return <AppScreen edges={['left', 'right', 'bottom']}><AppStateView state="loading" /></AppScreen>; if (query.error) return <AppScreen edges={['left', 'right', 'bottom']}><AppStateView message={errorMessage(query.error, t('addressTypes.loadFailed'))} onRetry={() => void query.refetch()} state="error" /></AppScreen>;
  return <AppScreen contentContainerStyle={styles.screen} edges={['left', 'right', 'bottom']} refreshControl={<RefreshControl colors={[theme.colors.primary]} onRefresh={() => void query.refetch()} refreshing={query.isRefetching} tintColor={theme.colors.primary} />}><AppListScreen<AddressType, 'table' | 'cards' | 'chart' | 'report' | 'import'> aboveViews={selectedIds.length && canDelete ? <AppButton icon="archive-outline" onPress={() => setPending({ kind: 'bulk' })} variant="outline">{t('addressTypes.archiveSelected', { count: selectedIds.length })}</AppButton> : null} defaultView="table" emptyContent={<AppStateView message={t('addressTypes.empty')} state="empty" />} fillViewSelector filterControl={<AddressTypeFilterButton field={field} onApply={applyFilters} operator={operator} status={list.state.filters.status} />} isFetching={query.isFetching} items={rows} onSearchChange={changeSearch} searchPlaceholder={t('addressTypes.search')} searchActions={canCreate ? <AppIconButton color={theme.colors.onPrimary} icon="add-outline" label={t('addressTypes.addAddressType')} onPress={() => openForm('create', null)} size={22} style={({ pressed }) => ({ backgroundColor: theme.colors.primary, opacity: pressed ? 0.75 : 1 })} /> : null} searchValue={list.searchInput} serverPagination={{ onPageChange: changePage, onPageSizeChange: changePageSize, page: list.state.page, pageSize: list.state.pageSize, pageSizeOptions: [3, 5, 10], totalItems: query.data?.metaData.totalCount ?? 0 }} showResultCount={false} showViewLabels views={[
    { value: 'table', icon: 'grid-outline', label: t('multiView.table'), defaultPageSize: 5, render: (items) => <AppDataTable columns={columns} getRowKey={(item) => item.id} rows={items} showPagination={false} serverState={{ onPageChange: changePage, onPageSizeChange: changePageSize, onSortChange: changeSort, page: list.state.page, pageSize: list.state.pageSize, sort: list.state.sort, totalRows: query.data?.metaData.totalCount ?? 0 }} /> },
    { value: 'cards', icon: 'albums-outline', label: t('multiView.cards'), defaultPageSize: 3, scrollable: true, render: (items) => <View style={styles.cards}>{items.map((item) => <AddressTypeCard addressType={item} canDelete={canDelete} canEdit={canEdit} key={item.id} onArchive={(value) => setPending({ kind: 'archive', value })} onEdit={(value) => openForm('edit', value)} onRestore={(value) => void restore(value)} onToggleSelection={toggle} onView={(value) => openForm('view', value)} selected={selectedIds.includes(item.id)} />)}</View> },
    { value: 'chart', icon: 'stats-chart-outline', label: t('addressTypes.chartView'), paginate: false, renderWhenEmpty: true, scrollable: true, render: (items) => <AddressTypesChartView addressTypes={items} totalCount={query.data?.metaData.totalCount ?? 0} /> },
    ...(reportAllowed ? [{ value: 'report' as const, icon: 'document-text-outline' as const, label: t('addressTypes.reportView'), paginate: false, renderWhenEmpty: true, render: () => <AddressTypeReportView /> }] : []),
    ...(canCreate ? [{ value: 'import' as const, icon: 'cloud-upload-outline' as const, label: t('addressTypes.importView'), paginate: false, renderWhenEmpty: true, scrollable: true, render: () => <AddressTypeImportView /> }] : []),
  ]} />{selected || formMode === 'create' ? <AddressTypeForm addressType={selected} loading={saveMutation.isPending} mode={formMode} onClose={closeForm} onSave={save} /> : null}<ConfirmationDialog confirmLabel={t('addressTypes.archive')} description={t(pending?.kind === 'bulk' ? 'addressTypes.bulkArchiveDescription' : 'addressTypes.archiveDescription', { count: selectedIds.length, name: pending?.kind === 'archive' ? pending.value.nameEn : '' })} loading={archiveMutation.isPending || bulkMutation.isPending} onCancel={() => setPending(null)} onConfirm={() => void confirm()} title={t(pending?.kind === 'bulk' ? 'addressTypes.bulkArchiveTitle' : 'addressTypes.archiveTitle')} tone="warning" visible={pending !== null} /></AppScreen>;
}
function errorMessage(error: unknown, fallback: string) { return error instanceof ApiError || error instanceof Error ? error.message || fallback : fallback; }
function formatDate(value: string, locale: string): string { const date = new Date(value); return Number.isNaN(date.getTime()) ? value : new Intl.DateTimeFormat(locale, { dateStyle: 'medium' }).format(date); }
const styles = StyleSheet.create({ screen: { gap: 12, paddingVertical: 8 }, actions: { flexDirection: 'row', justifyContent: 'center', gap: 4 }, cards: { gap: 6 } });
