// Mirrors the current module-owned backend permission catalogs; parity is enforced by a test.
export const permissions = {
  ViewAddresses: "Addresses:View",
  CreateAddresses: "Addresses:Create",
  EditAddresses: "Addresses:Edit",
  DeleteAddresses: "Addresses:Delete",
  ViewAddressTypes: "AddressTypes:View",
  CreateAddressTypes: "AddressTypes:Create",
  EditAddressTypes: "AddressTypes:Edit",
  ArchiveAddressTypes: "AddressTypes:Archive",
  RestoreAddressTypes: "AddressTypes:Restore",
  ViewApiKeys: "ApiKeys:View",
  CreateApiKeys: "ApiKeys:Create",
  EditApiKeys: "ApiKeys:Edit",
  RevokeApiKeys: "ApiKeys:Revoke",
  ViewBackups: "Backups:View",
  CreateBackups: "Backups:Create",
  RestoreBackups: "Backups:Restore",
  DeleteBackups: "Backups:Delete",
  ViewCategories: "Categories:View",
  CreateCategories: "Categories:Create",
  EditCategories: "Categories:Edit",
  DeleteCategories: "Categories:Delete",
  ViewAppointments: "Appointments:View",
  CreateAppointments: "Appointments:Create",
  EditAppointments: "Appointments:Edit",
  DeleteAppointments: "Appointments:Delete",
  ViewContactsParties: "ContactsParties:View",
  CreateContactsParties: "ContactsParties:Create",
  EditContactsParties: "ContactsParties:Edit",
  ViewCountries: "Countries:View",
  CreateCountries: "Countries:Create",
  EditCountries: "Countries:Edit",
  ArchiveCountries: "Countries:Archive",
  RestoreCountries: "Countries:Restore",
  ViewCompanyGeographicScope: "CompanyGeographicScope:View",
  EditCompanyGeographicScope: "CompanyGeographicScope:Edit",
  ViewOrganizationalStructure: "OrganizationalStructure:View",
  CreateOrganizationalStructure: "OrganizationalStructure:Create",
  EditOrganizationalStructure: "OrganizationalStructure:Edit",
  ArchiveOrganizationalStructure: "OrganizationalStructure:Archive",
  RestoreOrganizationalStructure: "OrganizationalStructure:Restore",
  ApproveJobDescriptions: "OrganizationalStructure:ApproveJobDescriptions",
  ViewRecruitment: "Recruitment:View",
  CreateJobRequisitions: "JobRequisitions:Create",
  SubmitJobRequisitions: "JobRequisitions:Submit",
  ReviewJobRequisitions: "JobRequisitions:Review",
  CancelJobRequisitions: "JobRequisitions:Cancel",
  CreateJobOpenings: "JobOpenings:Create",
  OpenJobOpenings: "JobOpenings:Open",
  PauseJobOpenings: "JobOpenings:Pause",
  CloseJobOpenings: "JobOpenings:Close",
  CreateJobPostings: "JobPostings:Create",
  EditJobPostings: "JobPostings:Edit",
  PublishJobPostings: "JobPostings:Publish",
  CloseJobPostings: "JobPostings:Close",
  CreateCandidates: "Candidates:Create",
  EditCandidates: "Candidates:Edit",
  CreateEmploymentApplications: "EmploymentApplications:Create",
  MoveEmploymentApplications: "EmploymentApplications:Move",
  RejectEmploymentApplications: "EmploymentApplications:Reject",
  WithdrawEmploymentApplications: "EmploymentApplications:Withdraw",
  HireCandidate: "EmploymentApplications:Hire",
  ScheduleInterviews: "Interviews:Schedule",
  CancelInterviews: "Interviews:Cancel",
  CompleteInterviews: "Interviews:Complete",
  EvaluateInterviews: "Interviews:Evaluate",
  CreateJobOffers: "JobOffers:Create",
  SubmitJobOffers: "JobOffers:Submit",
  ReviewJobOffers: "JobOffers:Review",
  IssueJobOffers: "JobOffers:Issue",
  RespondJobOffers: "JobOffers:Respond",
  EditRecruitmentSettings: "RecruitmentSettings:Edit",
  ViewFiscalYears: "FiscalYears:View",
  CreateFiscalYears: "FiscalYears:Create",
  EditFiscalYears: "FiscalYears:Edit",
  ArchiveFiscalYears: "FiscalYears:Archive",
  RestoreFiscalYears: "FiscalYears:Restore",
  OpenFiscalYears: "FiscalYears:Open",
  BeginClosingFiscalYears: "FiscalYears:BeginClosing",
  CloseFiscalYears: "FiscalYears:Close",
  LockFiscalYears: "FiscalYears:Lock",
  ReopenFiscalYears: "FiscalYears:Reopen",
  ViewCurrencies: "Currencies:View",
  CreateCurrencies: "Currencies:Create",
  EditCurrencies: "Currencies:Edit",
  ArchiveCurrencies: "Currencies:Archive",
  RestoreCurrencies: "Currencies:Restore",
  ViewAccountingSettings: "AccountingSettings:View",
  EditAccountingSettings: "AccountingSettings:Edit",
  ViewAccountHierarchyLevels: "AccountHierarchyLevels:View",
  CreateAccountHierarchyLevels: "AccountHierarchyLevels:Create",
  EditAccountHierarchyLevels: "AccountHierarchyLevels:Edit",
  ArchiveAccountHierarchyLevels: "AccountHierarchyLevels:Archive",
  RestoreAccountHierarchyLevels: "AccountHierarchyLevels:Restore",
  ViewAccounts: "Accounts:View",
  CreateAccounts: "Accounts:Create",
  EditAccounts: "Accounts:Edit",
  ArchiveAccounts: "Accounts:Archive",
  RestoreAccounts: "Accounts:Restore",
  ViewDimensionDefinitions: "DimensionDefinitions:View",
  CreateDimensionDefinitions: "DimensionDefinitions:Create",
  EditDimensionDefinitions: "DimensionDefinitions:Edit",
  ArchiveDimensionDefinitions: "DimensionDefinitions:Archive",
  RestoreDimensionDefinitions: "DimensionDefinitions:Restore",
  ViewDimensionValues: "DimensionValues:View",
  CreateDimensionValues: "DimensionValues:Create",
  EditDimensionValues: "DimensionValues:Edit",
  ArchiveDimensionValues: "DimensionValues:Archive",
  RestoreDimensionValues: "DimensionValues:Restore",
  ViewAccountDimensionPolicies: "AccountDimensionPolicies:View",
  EditAccountDimensionPolicies: "AccountDimensionPolicies:Edit",
  ViewBooks: "Books:View",
  CreateBooks: "Books:Create",
  EditBooks: "Books:Edit",
  ArchiveBooks: "Books:Archive",
  RestoreBooks: "Books:Restore",
  ViewJournalDefinitions: "JournalDefinitions:View",
  CreateJournalDefinitions: "JournalDefinitions:Create",
  EditJournalDefinitions: "JournalDefinitions:Edit",
  ArchiveJournalDefinitions: "JournalDefinitions:Archive",
  RestoreJournalDefinitions: "JournalDefinitions:Restore",
  ViewExchangeRateTypes: "ExchangeRateTypes:View",
  CreateExchangeRateTypes: "ExchangeRateTypes:Create",
  EditExchangeRateTypes: "ExchangeRateTypes:Edit",
  ArchiveExchangeRateTypes: "ExchangeRateTypes:Archive",
  RestoreExchangeRateTypes: "ExchangeRateTypes:Restore",
  ViewExchangeRates: "ExchangeRates:View",
  CreateExchangeRates: "ExchangeRates:Create",
  EditExchangeRates: "ExchangeRates:Edit",
  ViewAccountMappings: "AccountMappings:View",
  CreateAccountMappings: "AccountMappings:Create",
  EditAccountMappings: "AccountMappings:Edit",
  ViewPostingProfiles: "PostingProfiles:View",
  CreatePostingProfiles: "PostingProfiles:Create",
  EditPostingProfiles: "PostingProfiles:Edit",
  ResolvePostingProfiles: "PostingProfiles:Resolve",
  GenerateInvoiceQrCode: "Invoices:GenerateQrCode",
  ViewWorkforcePlans: "WorkforcePlans:View",
  CreateWorkforcePlans: "WorkforcePlans:Create",
  EditWorkforcePlans: "WorkforcePlans:Edit",
  ArchiveWorkforcePlans: "WorkforcePlans:Archive",
  RestoreWorkforcePlans: "WorkforcePlans:Restore",
  ApproveWorkforcePlans: "WorkforcePlans:Approve",
  ViewWorkforceBudgets: "WorkforceBudgets:View",
  CreateWorkforceBudgets: "WorkforceBudgets:Create",
  EditWorkforceBudgets: "WorkforceBudgets:Edit",
  SubmitWorkforceBudgets: "WorkforceBudgets:Submit",
  ReviewWorkforceBudgets: "WorkforceBudgets:Review",
  ViewPositionEnvelopes: "PositionEnvelopes:View",
  ViewEnvelopeAmendments: "EnvelopeAmendments:View",
  CreateEnvelopeAmendments: "EnvelopeAmendments:Create",
  ApproveEnvelopeAmendments: "EnvelopeAmendments:Approve",
  ViewStaffingRequests: "StaffingRequests:View",
  CreateStaffingRequests: "StaffingRequests:Create",
  ApproveStaffingRequests: "StaffingRequests:Approve",
  ViewWorkforceTrace: "WorkforcePlanning:ViewTrace",
  ViewWorkforceFinancials: "WorkforcePlanning:ViewFinancials",
  ViewDistricts: "Districts:View",
  CreateDistricts: "Districts:Create",
  EditDistricts: "Districts:Edit",
  ArchiveDistricts: "Districts:Archive",
  RestoreDistricts: "Districts:Restore",
  ViewChangeLogs: "ChangeLogs:View",
  ViewHangfireDashboard: "Hangfire:View",
  ViewDashboard: "Analytics:ViewDashboard",
  ExportData: "Analytics:Export",
  ViewDatabaseViews: "DatabaseViews:View",
  EditDatabaseViews: "DatabaseViews:Edit",
  DeleteDatabaseViews: "DatabaseViews:Delete",
  ViewLocalizations: "Localizations:View",
  CreateLocalizations: "Localizations:Create",
  EditLocalizations: "Localizations:Edit",
  DeleteLocalizations: "Localizations:Delete",
  ViewReportsCategories: "ReportsCategories:View",
  CreateReportsCategories: "ReportsCategories:Create",
  EditReportsCategories: "ReportsCategories:Edit",
  DeleteReportsCategories: "ReportsCategories:Delete",
  ViewReportTemplates: "ReportTemplates:View",
  CreateReportTemplates: "ReportTemplates:Create",
  EditReportTemplates: "ReportTemplates:Edit",
  PublishReportTemplates: "ReportTemplates:Publish",
  UnpublishReportTemplates: "ReportTemplates:Unpublish",
  ArchiveReportTemplates: "ReportTemplates:Archive",
  RestoreReportTemplates: "ReportTemplates:Restore",
  ViewCrystalReports: "CrystalReports:View",
  ViewGlobalCrystalReports: "GlobalCrystalReports:View",
  CreateCrystalReports: "CrystalReports:Create",
  DownloadCrystalReports: "CrystalReports:Download",
  UploadCrystalReports: "CrystalReports:Upload",
  PublishCrystalReports: "CrystalReports:Publish",
  ViewCrystalReportAccess: "CrystalReportAccess:View",
  EditCrystalReportAccess: "CrystalReportAccess:Edit",
  ArchiveCrystalReports: "CrystalReports:Archive",
  ViewRoles: "Roles:View",
  CreateRoles: "Roles:Create",
  EditRoles: "Roles:Edit",
  SetRoleStatus: "Roles:SetStatus",
  ViewRolePermissions: "RolePermissions:View",
  EditRolePermissions: "RolePermissions:Edit",
  ViewOfflineOperations: "OfflineOperations:View",
  EditOfflineOperations: "OfflineOperations:Edit",
  ViewStates: "States:View",
  CreateStates: "States:Create",
  EditStates: "States:Edit",
  ArchiveStates: "States:Archive",
  RestoreStates: "States:Restore",
  ViewSubCategories: "SubCategories:View",
  CreateSubCategories: "SubCategories:Create",
  EditSubCategories: "SubCategories:Edit",
  DeleteSubCategories: "SubCategories:Delete",
  ViewUsers: "Users:View",
  CreateUsers: "Users:Create",
  EditUsers: "Users:Edit",
  ResetUserPasswords: "Users:ResetPassword",
  SetUserStatus: "Users:SetStatus",
  UnlockUsers: "Users:Unlock",
  ArchiveUsers: "Users:Archive",
  RestoreUsers: "Users:Restore",
  ViewUserInvitations: "UserInvitations:View",
  CreateUserInvitations: "UserInvitations:Create",
  ResendUserInvitations: "UserInvitations:Resend",
  RevokeUserInvitations: "UserInvitations:Revoke",
  ViewAttendanceDevices: "AttendanceDevices:View",
  CreateAttendanceDevices: "AttendanceDevices:Create",
  EditAttendanceDevices: "AttendanceDevices:Edit",
  SetAttendanceDeviceStatus: "AttendanceDevices:SetStatus",
  EditAttendanceDeviceCredentials: "AttendanceDevices:EditCredentials",
  CreateAttendanceAgents: "AttendanceAgents:Create",
  DetectAttendanceDevices: "AttendanceDevices:Detect",
  TestAttendanceDevices: "AttendanceDevices:Test",
  PullAttendanceDeviceUsers: "AttendanceDevices:PullUsers",
  PullAttendance: "AttendanceDevices:PullAttendance",
  ViewRawAttendanceDevices: "AttendanceDevices:ViewRaw",
} as const;

export type PermissionString =
  (typeof permissions)[keyof typeof permissions];

export type PermissionModule =
  PermissionString extends `${infer Module}:${string}` ? Module : never;

export const getAllPermissions = (): PermissionString[] =>
  Object.values(permissions);

export const getPermissionModule = (
  permission: PermissionString
): PermissionModule => {
  const parts = permission.split(":");
  if (parts.length !== 2 || !parts[0] || !parts[1]) {
    throw new Error(`Invalid permission format: "${permission}". Expected "Module:Action".`);
  }
  return parts[0] as PermissionModule;
};

export const getAllPermissionModules = (): PermissionModule[] => [
  ...new Set(getAllPermissions().map(getPermissionModule)),
];

// Cache permission sets for performance (avoids repeated array iterations)
const permissionSetCache = new WeakMap<readonly string[], Set<string>>();

function getPermissionSet(userPermissions: readonly string[]): Set<string> {
  let cached = permissionSetCache.get(userPermissions);
  if (!cached) {
    cached = new Set(userPermissions);
    permissionSetCache.set(userPermissions, cached);
  }
  return cached;
}

export const hasPermission = (
  userPermissions: readonly string[],
  permission: PermissionString
): boolean => getPermissionSet(userPermissions).has(permission);

export const hasAnyPermission = (
  userPermissions: readonly string[],
  requiredPermissions: readonly PermissionString[]
): boolean => {
  const permissionSet = getPermissionSet(userPermissions);
  return requiredPermissions.some((permission) => permissionSet.has(permission));
};

export const hasAllPermissions = (
  userPermissions: readonly string[],
  requiredPermissions: readonly PermissionString[]
): boolean => {
  const permissionSet = getPermissionSet(userPermissions);
  return requiredPermissions.every((permission) => permissionSet.has(permission));
};
