import { renderHook } from '@testing-library/react-native';
import { addressTypeApi } from '../api/address-type-api';
import { addressTypeKeys } from './address-type-keys';
import { useArchiveAddressType, useBulkArchiveAddressTypes, useBulkCreateAddressTypes, useRestoreAddressType, useSaveAddressType } from './use-address-types';
const mockInvalidate = jest.fn(); const mockUseMutation = jest.fn((options: unknown) => options);
jest.mock('@tanstack/react-query', () => ({ useMutation: (options: unknown) => mockUseMutation(options), useQuery: jest.fn(), useQueryClient: () => ({ invalidateQueries: mockInvalidate }) }));
jest.mock('../api/address-type-api', () => ({ addressTypeApi: { archive: jest.fn(), bulkArchive: jest.fn(), bulkCreate: jest.fn(), create: jest.fn(), getPage: jest.fn(), restore: jest.fn(), update: jest.fn() } }));
type Contract<T> = { mutationFn: (variables: T) => Promise<unknown>; onSuccess: () => Promise<unknown> };
describe('Address Type mutation hooks', () => { beforeEach(() => { jest.clearAllMocks(); mockInvalidate.mockResolvedValue(undefined); }); it.each([['archive', useArchiveAddressType, 7, addressTypeApi.archive], ['restore', useRestoreAddressType, 7, addressTypeApi.restore], ['bulk archive', useBulkArchiveAddressTypes, [3, 7], addressTypeApi.bulkArchive], ['bulk create', useBulkCreateAddressTypes, [{ nameAr: 'منزل', nameEn: 'Home' }], addressTypeApi.bulkCreate]] as const)('invalidates Address Types after %s', async (_name, hookFactory, variables, apiMethod) => { const hook = await renderHook(() => hookFactory()); const mutation = hook.result.current as unknown as Contract<typeof variables>; await mutation.mutationFn(variables); expect(apiMethod).toHaveBeenCalledWith(variables); await mutation.onSuccess(); expect(mockInvalidate).toHaveBeenCalledWith({ queryKey: addressTypeKeys.all }); }); it('chooses create or update based on nullable ID', async () => { const hook = await renderHook(() => useSaveAddressType()); const mutation = hook.result.current as unknown as Contract<{ id: number | null; request: { nameAr: string; nameEn: string } }>; const request = { nameAr: 'منزل', nameEn: 'Home' }; await mutation.mutationFn({ id: null, request }); await mutation.mutationFn({ id: 7, request }); expect(addressTypeApi.create).toHaveBeenCalledWith(request); expect(addressTypeApi.update).toHaveBeenCalledWith(7, request); }); });
