// <auto-generated />
using HrManagementSystem.Features.Platform.Notifications.Entities;
using HrManagementSystem.Infrastructure.Persistance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace HrManagementSystem.Infrastructure.Migrations;

[DbContext(typeof(ApplicationDbContext))]
[Migration("20260713083847_modifyLogging")]
partial class modifyLogging
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
        AddNotifications.BuildModel(modelBuilder);
        modelBuilder.Ignore<Notification>();
    }
}
