// Global Presence Row data
export const hrTimeline = [
  {
    id: "leadership-training",
    date: "2025-10-28",
    title: "Leadership Training Completed",
    description: "Completed Q4 leadership development program across EMEA",
    status: "success",
    value: 42,
    category: "Learning",
    priority: "medium",
  },
  {
    id: "campus-hiring",
    date: "2025-10-25",
    title: "Campus Hiring Drive",
    description: "Closed 12 graduate hires in North America",
    status: "info",
    value: 12,
    category: "Hiring",
    priority: "low",
  },
  {
    id: "remote-work-policy",
    date: "2025-10-19",
    title: "Policy Update: Remote Work",
    description: "Updated remote work policy with flexible hours guidance",
    status: "warning",
    value: 1,
    category: "Policy",
    priority: "high",
  },
  {
    id: "attrition-analysis",
    date: "2025-10-10",
    title: "Attrition Spike Analysis",
    description: "Completed root-cause analysis for APAC attrition spike",
    status: "error",
    value: 6,
    category: "Attrition",
    priority: "high",
  },
];

export interface GlobalPresenceCountry {
  id: string;
  name: string;
  employees: number;
  offices: number;
  revenue: number;
  currency: string;
  timezone: string;
  flag: string;
  coordinates: [number, number];
}

export const worldData: GlobalPresenceCountry[] = [
  {
    id: "US",
    name: "United States",
    employees: 520,
    offices: 4,
    revenue: 1850000,
    currency: "USD",
    timezone: "UTC-5 to -8",
    flag: "🇺🇸",
    coordinates: [-98.5, 39.8],
  },
  {
    id: "GB",
    name: "United Kingdom",
    employees: 120,
    offices: 1,
    revenue: 380000,
    currency: "GBP",
    timezone: "UTC+0",
    flag: "🇬🇧",
    coordinates: [-3.4, 55.4],
  },
  {
    id: "DE",
    name: "Germany",
    employees: 160,
    offices: 1,
    revenue: 420000,
    currency: "EUR",
    timezone: "UTC+1",
    flag: "🇩🇪",
    coordinates: [10.4, 51.1],
  },
  {
    id: "IN",
    name: "India",
    employees: 260,
    offices: 2,
    revenue: 520000,
    currency: "INR",
    timezone: "UTC+5:30",
    flag: "🇮🇳",
    coordinates: [78.9, 22.1],
  },
  {
    id: "CN",
    name: "China",
    employees: 80,
    offices: 1,
    revenue: 260000,
    currency: "CNY",
    timezone: "UTC+8",
    flag: "🇨🇳",
    coordinates: [104.1, 35.8],
  },
  {
    id: "JP",
    name: "Japan",
    employees: 40,
    offices: 1,
    revenue: 210000,
    currency: "JPY",
    timezone: "UTC+9",
    flag: "🇯🇵",
    coordinates: [138.3, 36.2],
  },
  {
    id: "AU",
    name: "Australia",
    employees: 28,
    offices: 1,
    revenue: 90000,
    currency: "AUD",
    timezone: "UTC+10",
    flag: "🇦🇺",
    coordinates: [134.5, -25.7],
  },
  {
    id: "EG",
    name: "Egypt",
    employees: 24,
    offices: 1,
    revenue: 82000,
    currency: "EGP",
    timezone: "UTC+2",
    flag: "🇪🇬",
    coordinates: [30.8, 26.8],
  },
  {
    id: "ZA",
    name: "South Africa",
    employees: 20,
    offices: 1,
    revenue: 76000,
    currency: "ZAR",
    timezone: "UTC+2",
    flag: "🇿🇦",
    coordinates: [24.7, -29],
  },
  {
    id: "BR",
    name: "Brazil",
    employees: 32,
    offices: 1,
    revenue: 110000,
    currency: "BRL",
    timezone: "UTC-3",
    flag: "🇧🇷",
    coordinates: [-51.9, -10.8],
  },
];
