import { StyleSheet, View } from 'react-native';
import { useTranslation } from 'react-i18next';
import { useAppTheme } from '@/src/core/theme';
import { AppDataCard, AppIcon, AppIconButton, AppStatusBadge, AppText } from '@/src/shared/components';
import type { State } from '../types/state';

interface Props { state: State; canEdit: boolean; canDelete: boolean; selected: boolean; active?: boolean; flash?: boolean; flashToken?: string | number; onEdit: (state: State) => void; onArchive: (state: State) => void; onRestore: (state: State) => void; onView: (state: State) => void; onToggleSelection: (state: State) => void; }
export function StateCard({ state, canEdit, canDelete, selected, active = false, flash = false, flashToken, onEdit, onArchive, onRestore, onView, onToggleSelection }: Props) {
  const { t } = useTranslation(); const { theme } = useAppTheme(); const archived = state.isDeleted;
  return <AppDataCard active={active} flash={flash} flashToken={flashToken} padding="sm" selected={selected} style={styles.card}><View style={styles.header}><View style={[styles.icon, { backgroundColor: theme.colors.surfaceMuted, borderRadius: theme.radius.sm }]}><AppIcon color={theme.colors.primary} name="map-outline" size={21} /></View><View style={styles.name}><AppText numberOfLines={1} variant="label">{state.nameEn}</AppText><AppText color="muted" numberOfLines={1} variant="bodySmall">{state.nameAr}</AppText></View><AppStatusBadge color={archived ? theme.colors.warning : theme.colors.success} label={t(archived ? 'states.archived' : 'states.active')} /></View><View style={styles.details}><AppText color="muted" variant="caption">{state.code} · {state.country.nameEn}</AppText><AppText color="muted" variant="caption">{t('states.districtsCount', { count: state.districtsCount })}</AppText></View><View style={styles.actions}>{canDelete && !archived ? <AppIconButton accessibilityState={{ selected }} color={selected ? theme.colors.accent : undefined} icon={selected ? 'checkbox' : 'square-outline'} label={t('states.selectState', { name: state.nameEn })} onPress={() => onToggleSelection(state)} /> : null}<AppIconButton icon="eye-outline" label={t('states.viewState')} onPress={() => onView(state)} />{canEdit && !archived ? <AppIconButton icon="create-outline" label={t('states.editState')} onPress={() => onEdit(state)} /> : null}{canDelete ? <AppIconButton icon={archived ? 'refresh-outline' : 'archive-outline'} label={t(archived ? 'states.restore' : 'states.archive')} onPress={() => archived ? onRestore(state) : onArchive(state)} /> : null}</View></AppDataCard>;
}
const styles = StyleSheet.create({ card: { gap: 5 }, header: { flexDirection: 'row', alignItems: 'center', gap: 6 }, icon: { width: 36, height: 36, alignItems: 'center', justifyContent: 'center' }, name: { flex: 1, minWidth: 0, gap: 1 }, details: { gap: 2 }, actions: { flexDirection: 'row', justifyContent: 'flex-end' } });
