// Generates the web artifacts from the TypeScript token source.
// Requires Node >= 22.18 (built-in TypeScript type stripping).
//   dist/tokens.css  CSS variables (shadcn names + extensions) per palette and mode
//   dist/theme.css   Tailwind v4 @theme mapping for shadcn/ui
//   dist/tokens.json Flat JSON for design tools and documentation
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import {
  breakpoints,
  chartColors,
  defaultPalette,
  elevation,
  fontStack,
  layout,
  motion,
  palettes,
  radius,
  spacing,
  textStyles,
  themePaletteOrder,
  zIndex,
} from '../src/index.ts';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const dist = resolve(root, 'dist');
mkdirSync(dist, { recursive: true });

const rem = (px) => (px === 0 ? '0' : `${+(px / 16).toFixed(4)}rem`);
const header = '/* Generated by @app/tokens (scripts/build.mjs). Do not edit by hand. */\n';

function colorVariables(colors) {
  const chart = chartColors(colors);
  const vars = {
    background: colors.background,
    foreground: colors.foreground,
    card: colors.surface,
    'card-foreground': colors.surfaceForeground,
    popover: colors.surface,
    'popover-foreground': colors.surfaceForeground,
    surface: colors.surface,
    'surface-foreground': colors.surfaceForeground,
    primary: colors.primary,
    'primary-foreground': colors.primaryForeground,
    secondary: colors.secondary,
    'secondary-foreground': colors.secondaryForeground,
    muted: colors.muted,
    'muted-foreground': colors.mutedForeground,
    accent: colors.accent,
    'accent-foreground': colors.accentForeground,
    destructive: colors.destructive,
    'destructive-foreground': colors.destructiveForeground,
    'brand-2': colors.brand2,
    'brand-2-foreground': colors.brand2Foreground,
    'brand-3': colors.brand3,
    'brand-3-foreground': colors.brand3Foreground,
    success: colors.success,
    'success-foreground': colors.successForeground,
    warning: colors.warning,
    'warning-foreground': colors.warningForeground,
    info: colors.info,
    'info-foreground': colors.infoForeground,
    border: colors.border,
    input: colors.input,
    ring: colors.ring,
    disabled: colors.disabled,
    overlay: colors.overlay,
    sidebar: colors.surface,
    'sidebar-foreground': colors.surfaceForeground,
    'sidebar-primary': colors.primary,
    'sidebar-primary-foreground': colors.primaryForeground,
    'sidebar-accent': colors.muted,
    'sidebar-accent-foreground': colors.foreground,
    'sidebar-border': colors.border,
    'sidebar-ring': colors.ring,
  };
  chart.forEach((value, index) => { vars[`chart-${index + 1}`] = value; });
  return vars;
}

function block(selector, vars, indent = '  ') {
  const lines = Object.entries(vars).map(([name, value]) => `${indent}--${name}: ${value};`);
  return `${selector} {\n${lines.join('\n')}\n}\n`;
}

const staticVars = {
  radius: rem(radius.md),
  'app-font-sans': fontStack.sans,
  'app-font-mono': fontStack.mono,
  'content-max-width': rem(layout.contentMaxWidth),
  'wide-content-max-width': rem(layout.wideContentMaxWidth),
  'overlay-max-width': rem(layout.overlayMaxWidth),
  'sidebar-width': rem(layout.sidebarWidth),
  'sidebar-collapsed-width': rem(layout.sidebarCollapsedWidth),
  'touch-target': rem(layout.touchTarget),
  'duration-fast': `${motion.duration.fast}ms`,
  'duration-normal': `${motion.duration.normal}ms`,
  'duration-slow': `${motion.duration.slow}ms`,
  'ease-standard': motion.easing.standard,
  'ease-emphasized': motion.easing.emphasized,
};
for (const [name, value] of Object.entries(zIndex)) staticVars[`z-${name}`] = String(value);

let css = header;
css += '/* Usage: <html data-palette="green" class="dark" dir="rtl">. Without data-palette the default palette applies. */\n\n';
css += block(':root', { ...staticVars, ...colorVariables(palettes[defaultPalette].light) });
css += '\n' + block(':root.dark', colorVariables(palettes[defaultPalette].dark));
for (const palette of themePaletteOrder) {
  css += `\n/* ${palette} */\n`;
  css += block(`[data-palette="${palette}"]`, colorVariables(palettes[palette].light));
  css += block(`[data-palette="${palette}"].dark`, colorVariables(palettes[palette].dark));
}
css += '\n@media (prefers-reduced-motion: reduce) {\n  :root {\n    --duration-fast: 0ms;\n    --duration-normal: 0ms;\n    --duration-slow: 0ms;\n  }\n}\n';
writeFileSync(resolve(dist, 'tokens.css'), css);

// Tailwind v4 theme mapping (shadcn/ui convention).
const colorNames = Object.keys(colorVariables(palettes[defaultPalette].light));
let theme = header;
theme += '/* Import after tailwindcss and tokens.css:\n   @import "tailwindcss";\n   @import "@app/tokens/css";\n   @import "@app/tokens/tailwind"; */\n\n';
theme += '@custom-variant dark (&:where(.dark, .dark *));\n\n';
theme += '@theme inline {\n';
for (const name of colorNames) theme += `  --color-${name}: var(--${name});\n`;
theme += '  --font-sans: var(--app-font-sans);\n  --font-mono: var(--app-font-mono);\n';
for (const [name, value] of Object.entries(radius)) {
  if (name === 'none') continue;
  theme += `  --radius-${name}: ${name === 'full' ? '9999px' : rem(value)};\n`;
}
for (const [name, value] of Object.entries(elevation)) {
  if (name === 'none') continue;
  theme += `  --shadow-${name}: ${value.css};\n`;
}
for (const [name, value] of Object.entries(textStyles)) {
  theme += `  --text-${name}: ${rem(value.fontSize)};\n`;
  theme += `  --text-${name}--line-height: ${rem(value.lineHeight)};\n`;
  theme += `  --text-${name}--font-weight: ${value.fontWeight};\n`;
}
for (const [name, value] of Object.entries(breakpoints)) theme += `  --breakpoint-${name}: ${rem(value)};\n`;
theme += '  --animate-duration: var(--duration-normal);\n';
theme += '}\n';
writeFileSync(resolve(dist, 'theme.css'), theme);

const json = {
  palettes,
  spacing,
  radius,
  textStyles,
  fontStack,
  elevation: Object.fromEntries(Object.entries(elevation).map(([k, v]) => [k, v.css])),
  motion,
  layout,
  breakpoints,
  zIndex,
};
writeFileSync(resolve(dist, 'tokens.json'), JSON.stringify(json, null, 2) + '\n');

console.log(`Tokens built: ${themePaletteOrder.length} palettes x 2 modes -> dist/tokens.css, dist/theme.css, dist/tokens.json`);
