<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>ErpSystem.Modules.Accounting.Domain</AssemblyName>
    <RootNamespace>ErpSystem.Modules.Accounting.Domain</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup><ProjectReference Include="..\..\..\BuildingBlocks\ErpSystem.BuildingBlocks.Domain\ErpSystem.BuildingBlocks.Domain.csproj" /></ItemGroup>
</Project>
