import { useCallback, useMemo, useState } from 'react';
import { RefreshControl, StyleSheet, View } from 'react-native';
import { useTranslation } from 'react-i18next';
import { ApiError } from '@/src/core/api';
import { useAppTheme } from '@/src/core/theme';
import { permissions, useAuthorization } from '@/src/platform/auth';
import { toApiPageNumber, useServerListState } from '@/src/shared/listing';
import { AppDataCard, AppDataTable, type AppDataTableColumn, AppIconButton, AppListScreen, AppScreen, AppStateView, AppStatusBadge, AppText, AppTextField, ConfirmationDialog, showToast } from '@/src/shared/components';
import { EnvelopeAmendmentForm } from '../components/EnvelopeAmendmentForm';
import { StaffingFilterButton } from '../components/StaffingFilterButton';
import { useApproveEnvelopeAmendment, useCreateEnvelopeAmendment, useEnvelopeAmendment, useEnvelopeAmendments, useRejectEnvelopeAmendment, useSubmitEnvelopeAmendment } from '../queries/use-staffing';
import type { EnvelopeAmendment, EnvelopeAmendmentPageQuery, EnvelopeAmendmentRequest } from '../../domain/models/staffing';

type Pending = { kind: 'submit' | 'approve' | 'reject'; item: EnvelopeAmendment } | null;
interface Filters { status: string }
export function EnvelopeAmendmentsScreen() {
  const { t } = useTranslation(); const { theme } = useAppTheme();
  const { allowed: viewAllowed } = useAuthorization({ requiredPermissions: [permissions.ViewEnvelopeAmendments] });
  const { allowed: createAllowed } = useAuthorization({ requiredPermissions: [permissions.CreateEnvelopeAmendments] });
  const { allowed: approveAllowed } = useAuthorization({ requiredPermissions: [permissions.ApproveEnvelopeAmendments] });
  const list = useServerListState<EnvelopeAmendmentPageQuery['sortBy'], Filters>({ initialFilters: { status: 'all' }, initialPageSize: 5, initialSort: { columnId: 'createdOn', direction: 'descending' } });
  const args = useMemo<EnvelopeAmendmentPageQuery>(() => ({ pageNumber: toApiPageNumber(list.state.page), pageSize: list.state.pageSize, status: list.state.filters.status, search: list.state.search, sortBy: 'createdOn', sortDirection: list.state.sort?.direction === 'ascending' ? 'asc' : 'desc' }), [list.state]);
  const query = useEnvelopeAmendments(args); const create = useCreateEnvelopeAmendment(); const submit = useSubmitEnvelopeAmendment(); const approve = useApproveEnvelopeAmendment(); const reject = useRejectEnvelopeAmendment();
  const [formOpen, setFormOpen] = useState(false); const [viewMode, setViewMode] = useState(false); const [selected, setSelected] = useState<EnvelopeAmendment | null>(null); const [pending, setPending] = useState<Pending>(null); const [reason, setReason] = useState('');
  const detail = useEnvelopeAmendment(selected?.id ?? null, formOpen && viewMode);
  const openView = useCallback((item: EnvelopeAmendment) => { setSelected(item); setViewMode(true); setFormOpen(true); }, []);
  const save = useCallback(async (request: EnvelopeAmendmentRequest) => { try { await create.mutateAsync(request); showToast.success(t('staffing.messages.amendmentCreated')); setFormOpen(false); } catch (error) { showToast.error(error, t('staffing.messages.lifecycleError')); throw error; } }, [create, t]);
  const ask = useCallback((kind: NonNullable<Pending>['kind'], item: EnvelopeAmendment) => { setReason(''); setPending({ kind, item }); }, []);
  const confirm = useCallback(async () => { if (!pending) return; const action = { id: pending.item.id, rowVersion: pending.item.rowVersion }; try { if (pending.kind === 'submit') await submit.mutateAsync(action); else if (pending.kind === 'approve') await approve.mutateAsync(action); else { if (!reason.trim()) return; await reject.mutateAsync({ ...action, reason: reason.trim() }); } const key = pending.kind === 'submit' ? 'amendmentSubmitted' : pending.kind === 'approve' ? 'amendmentApproved' : 'amendmentRejected'; showToast.success(t(`staffing.messages.${key}`)); setPending(null); setSelected(null); } catch (error) { showToast.error(error, t('staffing.messages.lifecycleError')); } }, [approve, pending, reason, reject, submit, t]);
  const buttons = useCallback((item: EnvelopeAmendment) => <View style={styles.actions}><AppIconButton icon="eye-outline" label={t('common.view')} onPress={() => openView(item)} />{createAllowed && (item.status === 1 || item.status === 4) ? <AppIconButton icon="send-outline" label={t('staffing.actions.submit')} onPress={() => ask('submit', item)} /> : null}{approveAllowed && item.status === 2 ? <><AppIconButton icon="checkmark-outline" label={t('staffing.actions.approve')} onPress={() => ask('approve', item)} /><AppIconButton icon="close-outline" label={t('staffing.actions.reject')} onPress={() => ask('reject', item)} /></> : null}</View>, [approveAllowed, ask, createAllowed, openView, t]);
  const columns = useMemo<AppDataTableColumn<EnvelopeAmendment>[]>(() => [
    { id: 'envelopeCode', header: t('staffing.fields.envelope'), width: 170, render: item => <AppText weight="700">{item.envelopeCode}</AppText> },
    { id: 'status', header: t('staffing.fields.status'), width: 120, render: item => <AppStatusBadge color={item.status === 3 ? theme.colors.success : item.status === 4 ? theme.colors.danger : theme.colors.warning} label={t(`staffing.amendmentStatus.${item.status}`)} /> },
    { id: 'additionalHeadcount', header: t('staffing.fields.additionalHeadcount'), width: 170, render: item => <AppText>+{item.additionalHeadcount}</AppText> },
    { id: 'additionalSalaryCost', header: t('staffing.fields.additionalSalaryCost'), width: 190, render: item => <AppText>+{item.additionalSalaryCost}</AppText> },
    { id: 'actions', header: t('common.actions'), width: 170, align: 'center', render: buttons },
  ], [buttons, t, theme.colors.danger, theme.colors.success, theme.colors.warning]);
  if (!viewAllowed) return <AppScreen><AppStateView state="error" message={t('common.accessDenied')} /></AppScreen>;
  if (query.isLoading) return <AppScreen><AppStateView state="loading" /></AppScreen>;
  if (query.error) return <AppScreen><AppStateView state="error" message={errorMessage(query.error, t('staffing.messages.fetchError'))} onRetry={() => void query.refetch()} /></AppScreen>;
  const rows = query.data?.items ?? [];
  return <AppScreen edges={['left','right','bottom']} contentContainerStyle={styles.screen} refreshControl={<RefreshControl refreshing={query.isRefetching} onRefresh={() => void query.refetch()} tintColor={theme.colors.primary} colors={[theme.colors.primary]} />}>
    <AppListScreen<EnvelopeAmendment, 'table' | 'cards'> defaultView="table" items={rows} isFetching={query.isFetching} emptyContent={<AppStateView state="empty" message={t('staffing.amendments.empty')} />} fillViewSelector showViewLabels showResultCount={false} searchValue={list.searchInput} searchPlaceholder={t('staffing.search')} onSearchChange={list.setSearchInput} filterControl={<StaffingFilterButton amendment value={list.state.filters.status} onApply={status => { list.setFilters({ status }); list.setPage(0); }} />} searchActions={createAllowed ? <AppIconButton icon="add-outline" label={t('staffing.amendments.createTitle')} color={theme.colors.onPrimary} onPress={() => { setSelected(null); setViewMode(false); setFormOpen(true); }} size={22} style={({ pressed }) => ({ backgroundColor: theme.colors.primary, opacity: pressed ? .75 : 1 })} /> : null} serverPagination={{ page: list.state.page, pageSize: list.state.pageSize, totalItems: query.data?.metaData.totalCount ?? 0, pageSizeOptions: [3,5,10], onPageChange: list.setPage, onPageSizeChange: list.setPageSize }} views={[{ value: 'table', icon: 'grid-outline', label: t('multiView.table'), defaultPageSize: 5, render: items => <AppDataTable rows={items} columns={columns} getRowKey={item => item.id} showPagination={false} serverState={{ page: list.state.page, pageSize: list.state.pageSize, totalRows: query.data?.metaData.totalCount ?? 0, sort: list.state.sort, onPageChange: list.setPage, onPageSizeChange: list.setPageSize, onSortChange: sort => list.setSort(sort ? { ...sort, columnId: 'createdOn' } : null) }} /> }, { value: 'cards', icon: 'albums-outline', label: t('multiView.cards'), defaultPageSize: 3, scrollable: true, render: items => <View style={styles.cards}>{items.map(item => <AppDataCard key={item.id} padding="md"><View style={styles.cardHeader}><AppText weight="800">{item.envelopeCode}</AppText><AppStatusBadge color={item.status === 3 ? theme.colors.success : theme.colors.warning} label={t(`staffing.amendmentStatus.${item.status}`)} /></View><AppText>+{item.additionalHeadcount} · +{item.additionalSalaryCost}</AppText>{buttons(item)}</AppDataCard>)}</View> }]} />
    {formOpen ? <EnvelopeAmendmentForm visible item={viewMode ? detail.data ?? null : null} loading={create.isPending || detail.isFetching} onClose={() => setFormOpen(false)} onSave={save} /> : null}
    <ConfirmationDialog visible={pending !== null} title={t(`staffing.confirm.${pending?.kind ?? 'submit'}AmendmentTitle`)} description={t(`staffing.confirm.${pending?.kind ?? 'submit'}AmendmentDescription`)} confirmLabel={t(`staffing.actions.${pending?.kind ?? 'submit'}`)} tone={pending?.kind === 'reject' ? 'danger' : 'default'} loading={submit.isPending || approve.isPending || reject.isPending} onCancel={() => setPending(null)} onConfirm={confirm}>{pending?.kind === 'reject' ? <AppTextField multiline required label={t('staffing.fields.reason')} value={reason} onChangeText={setReason} error={!reason.trim() ? t('staffing.validation.justification') : undefined} /> : <AppText>{pending?.item.envelopeCode ?? ''}</AppText>}</ConfirmationDialog>
  </AppScreen>;
}
function errorMessage(error: unknown, fallback: string) { return error instanceof ApiError || error instanceof Error ? error.message || fallback : fallback; }
const styles = StyleSheet.create({ screen: { gap: 12, paddingVertical: 8 }, actions: { flexDirection: 'row', justifyContent: 'center', gap: 4, flexWrap: 'wrap' }, cards: { gap: 8 }, cardHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: 8 } });
