import { useCallback, useMemo, useState } from 'react';
import { RefreshControl, StyleSheet, View } from 'react-native';
import { useTranslation } from 'react-i18next';
import { ApiError } from '@/src/core/api';
import { useAppTheme } from '@/src/core/theme';
import { permissions, useAuthorization } from '@/src/platform/auth';
import { toApiPageNumber, useServerListState } from '@/src/shared/listing';
import { AppDataCard, AppDataTable, type AppDataTableColumn, AppIconButton, AppListScreen, AppScreen, AppSelectField, AppStateView, AppStatusBadge, AppText, AppTextField, ConfirmationDialog, showToast } from '@/src/shared/components';
import { StaffingFilterButton } from '../components/StaffingFilterButton';
import { StaffingRequestForm } from '../components/StaffingRequestForm';
import { useApproveStaffingRequest, useCloseStaffingRequest, useCreateStaffingRequest, useRejectStaffingRequest, useStaffingRequest, useStaffingRequests, useSubmitStaffingRequest } from '../queries/use-staffing';
import type { StaffingRequest, StaffingRequestCloseReason, StaffingRequestInput, StaffingRequestPageQuery } from '../../domain/models/staffing';

type Pending = { kind: 'submit' | 'approve' | 'reject' | 'close'; item: StaffingRequest } | null;
interface Filters { status: string }

export function StaffingRequestsScreen() {
  const { t } = useTranslation(); const { theme } = useAppTheme();
  const { allowed: viewAllowed } = useAuthorization({ requiredPermissions: [permissions.ViewStaffingRequests] });
  const { allowed: createAllowed } = useAuthorization({ requiredPermissions: [permissions.CreateStaffingRequests] });
  const { allowed: approveAllowed } = useAuthorization({ requiredPermissions: [permissions.ApproveStaffingRequests] });
  const list = useServerListState<StaffingRequestPageQuery['sortBy'], Filters>({ initialFilters: { status: 'all' }, initialPageSize: 5, initialSort: { columnId: 'createdOn', direction: 'descending' } });
  const args = useMemo<StaffingRequestPageQuery>(() => ({ pageNumber: toApiPageNumber(list.state.page), pageSize: list.state.pageSize, status: list.state.filters.status, search: list.state.search, sortBy: list.state.sort?.columnId ?? 'createdOn', sortDirection: list.state.sort?.direction === 'ascending' ? 'asc' : 'desc' }), [list.state]);
  const query = useStaffingRequests(args); const create = useCreateStaffingRequest(); const submit = useSubmitStaffingRequest(); const approve = useApproveStaffingRequest(); const reject = useRejectStaffingRequest(); const close = useCloseStaffingRequest();
  const [formOpen, setFormOpen] = useState(false); const [viewMode, setViewMode] = useState(false); const [selected, setSelected] = useState<StaffingRequest | null>(null); const [pending, setPending] = useState<Pending>(null); const [reason, setReason] = useState(''); const [closeReason, setCloseReason] = useState<StaffingRequestCloseReason>(2);
  const detail = useStaffingRequest(selected?.id ?? null, formOpen && viewMode);
  const openCreate = useCallback(() => { setSelected(null); setViewMode(false); setFormOpen(true); }, []);
  const openView = useCallback((item: StaffingRequest) => { setSelected(item); setViewMode(true); setFormOpen(true); }, []);
  const save = useCallback(async (request: StaffingRequestInput) => { try { await create.mutateAsync(request); showToast.success(t('staffing.messages.created')); setFormOpen(false); } catch (error) { showToast.error(error, t('staffing.messages.lifecycleError')); throw error; } }, [create, t]);
  const ask = useCallback((kind: NonNullable<Pending>['kind'], item: StaffingRequest) => { setReason(''); setCloseReason(item.remainingToHire === 0 ? 1 : item.remainingToHire < item.requestedHeadcount ? 3 : 2); setPending({ kind, item }); }, []);
  const confirm = useCallback(async () => { if (!pending) return; const action = { id: pending.item.id, rowVersion: pending.item.rowVersion }; try { if (pending.kind === 'submit') await submit.mutateAsync(action); else if (pending.kind === 'approve') await approve.mutateAsync(action); else if (pending.kind === 'reject') { if (!reason.trim()) return; await reject.mutateAsync({ ...action, reason: reason.trim() }); } else await close.mutateAsync({ ...action, closeReason }); const messageKey = pending.kind === 'submit' ? 'submitted' : pending.kind === 'approve' ? 'approved' : pending.kind === 'reject' ? 'rejected' : 'closed'; showToast.success(t(`staffing.messages.${messageKey}`)); setPending(null); setSelected(null); } catch (error) { showToast.error(error, t('staffing.messages.lifecycleError')); } }, [approve, close, closeReason, pending, reason, reject, submit, t]);
  const actionButtons = useCallback((item: StaffingRequest) => <View style={styles.actions}><AppIconButton icon="eye-outline" label={t('common.view')} onPress={() => openView(item)} />{createAllowed && (item.status === 1 || item.status === 4) ? <AppIconButton icon="send-outline" label={t('staffing.actions.submit')} onPress={() => ask('submit', item)} /> : null}{approveAllowed && item.status === 2 ? <><AppIconButton icon="checkmark-outline" label={t('staffing.actions.approve')} onPress={() => ask('approve', item)} /><AppIconButton icon="close-outline" label={t('staffing.actions.reject')} onPress={() => ask('reject', item)} /></> : null}{createAllowed && item.status === 3 ? <AppIconButton icon="archive-outline" label={t('staffing.actions.close')} onPress={() => ask('close', item)} /> : null}</View>, [approveAllowed, ask, createAllowed, openView, t]);
  const columns = useMemo<AppDataTableColumn<StaffingRequest>[]>(() => [
    { id: 'envelopeCode', header: t('staffing.fields.envelope'), width: 170, render: item => <AppText weight="700" variant="bodySmall">{item.envelopeCode}</AppText> },
    { id: 'status', header: t('staffing.fields.status'), width: 120, render: item => <AppStatusBadge color={item.status === 3 ? theme.colors.success : item.status === 4 ? theme.colors.danger : theme.colors.warning} label={t(`staffing.status.${item.status}`)} /> },
    { id: 'requestedHeadcount', header: t('staffing.fields.requestedHeadcount'), width: 145, render: item => <AppText>{item.requestedHeadcount}</AppText> },
    { id: 'remainingAllocatable', header: t('staffing.fields.remainingAllocatable'), width: 175, render: item => <AppText>{item.remainingAllocatable}</AppText> },
    { id: 'remainingToHire', header: t('staffing.fields.remainingToHire'), width: 155, render: item => <AppText>{item.remainingToHire}</AppText> },
    { id: 'actions', header: t('common.actions'), width: 190, align: 'center', render: actionButtons },
  ], [actionButtons, t, theme.colors.danger, theme.colors.success, theme.colors.warning]);
  if (!viewAllowed) return <AppScreen><AppStateView state="error" message={t('common.accessDenied')} /></AppScreen>;
  if (query.isLoading) return <AppScreen><AppStateView state="loading" /></AppScreen>;
  if (query.error) return <AppScreen><AppStateView state="error" message={errorMessage(query.error, t('staffing.messages.fetchError'))} onRetry={() => void query.refetch()} /></AppScreen>;
  const rows = query.data?.items ?? [];
  return <AppScreen edges={['left','right','bottom']} contentContainerStyle={styles.screen} refreshControl={<RefreshControl refreshing={query.isRefetching} onRefresh={() => void query.refetch()} tintColor={theme.colors.primary} colors={[theme.colors.primary]} />}>
    <AppListScreen<StaffingRequest, 'table' | 'cards'> defaultView="table" items={rows} isFetching={query.isFetching} emptyContent={<AppStateView state="empty" message={t('staffing.requests.empty')} />} fillViewSelector showViewLabels showResultCount={false} searchValue={list.searchInput} searchPlaceholder={t('staffing.search')} onSearchChange={list.setSearchInput} filterControl={<StaffingFilterButton value={list.state.filters.status} onApply={status => { list.setFilters({ status }); list.setPage(0); }} />} searchActions={createAllowed ? <AppIconButton icon="add-outline" label={t('staffing.requests.createTitle')} color={theme.colors.onPrimary} onPress={openCreate} size={22} style={({ pressed }) => ({ backgroundColor: theme.colors.primary, opacity: pressed ? .75 : 1 })} /> : null} serverPagination={{ page: list.state.page, pageSize: list.state.pageSize, totalItems: query.data?.metaData.totalCount ?? 0, pageSizeOptions: [3,5,10], onPageChange: list.setPage, onPageSizeChange: list.setPageSize }} views={[{ value: 'table', icon: 'grid-outline', label: t('multiView.table'), defaultPageSize: 5, render: items => <AppDataTable rows={items} columns={columns} getRowKey={item => item.id} showPagination={false} serverState={{ page: list.state.page, pageSize: list.state.pageSize, totalRows: query.data?.metaData.totalCount ?? 0, sort: list.state.sort, onPageChange: list.setPage, onPageSizeChange: list.setPageSize, onSortChange: sort => list.setSort(sort ? { ...sort, columnId: sort.columnId as StaffingRequestPageQuery['sortBy'] } : null) }} /> }, { value: 'cards', icon: 'albums-outline', label: t('multiView.cards'), defaultPageSize: 3, scrollable: true, render: items => <View style={styles.cards}>{items.map(item => <AppDataCard key={item.id} padding="md"><View style={styles.cardHeader}><AppText weight="800">{item.envelopeCode}</AppText><AppStatusBadge color={item.status === 3 ? theme.colors.success : theme.colors.warning} label={t(`staffing.status.${item.status}`)} /></View><AppText>{t('staffing.capacity.allocatable', { count: item.remainingAllocatable })} · {t('staffing.capacity.toHire', { count: item.remainingToHire })}</AppText><AppText color="muted">{item.totalReservedCost} · {item.targetStartDate}</AppText>{actionButtons(item)}</AppDataCard>)}</View> }]} />
    {formOpen ? <StaffingRequestForm visible mode={viewMode ? 'view' : 'create'} item={viewMode ? detail.data : null} detailLoading={viewMode && detail.isLoading} detailError={viewMode && detail.error ? errorMessage(detail.error, t('staffing.messages.fetchError')) : null} loading={create.isPending || detail.isFetching} onClose={() => setFormOpen(false)} onSave={save} /> : null}
    <ConfirmationDialog visible={pending !== null} title={t(`staffing.confirm.${pending?.kind ?? 'submit'}Title`)} description={t(`staffing.confirm.${pending?.kind ?? 'submit'}Description`)} confirmLabel={t(`staffing.actions.${pending?.kind ?? 'submit'}`)} tone={pending?.kind === 'reject' ? 'danger' : pending?.kind === 'close' ? 'warning' : 'default'} loading={submit.isPending || approve.isPending || reject.isPending || close.isPending} onCancel={() => setPending(null)} onConfirm={confirm}>
      {pending?.kind === 'reject' ? <AppTextField multiline required label={t('staffing.fields.reason')} value={reason} onChangeText={setReason} error={!reason.trim() ? t('staffing.validation.justification') : undefined} /> : pending?.kind === 'close' ? <AppSelectField label={t('staffing.fields.closeReason')} value={closeReason} onChange={value => setCloseReason(value as StaffingRequestCloseReason)} options={[1,2,3].map(value => ({ value, label: t(`staffing.closeReason.${value}`), icon: 'archive-outline' }))} /> : <AppText>{pending?.item.envelopeCode ?? ''}</AppText>}
    </ConfirmationDialog>
  </AppScreen>;
}
function errorMessage(error: unknown, fallback: string) { return error instanceof ApiError || error instanceof Error ? error.message || fallback : fallback; }
const styles = StyleSheet.create({ screen: { gap: 12, paddingVertical: 8 }, actions: { flexDirection: 'row', justifyContent: 'center', gap: 4, flexWrap: 'wrap' }, cards: { gap: 8 }, cardHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: 8 } });
