using ErpSystem.Modules.Accounting.Application.Features.Finance.LedgerSetup.Commands;
using ErpSystem.Modules.Accounting.Application.Features.Finance.LedgerSetup.Contracts;
using ErpSystem.Modules.Accounting.Application.Features.Finance.LedgerSetup.Queries;

namespace ErpSystem.Modules.Accounting.Presentation.Features.Finance.LedgerSetup.V1;
[ApiVersion("1.0")][Route("api/v{version:apiVersion}/accounting-dimensions")][ApiController][TenantMember]
public sealed class DimensionsController(ISender sender) : ControllerBase
{
    [HttpGet] [HasPermission(AccountingPermissions.ViewDimensionDefinitions)] public Task<IReadOnlyList<DimensionDefinitionResponse>> Definitions([FromQuery] GetDimensionDefinitionsQuery query, CancellationToken cancellationToken) => sender.Send(query, cancellationToken);
    [HttpGet("{definitionId:int}/values")] [HasPermission(AccountingPermissions.ViewDimensionValues)] public Task<IReadOnlyList<DimensionValueResponse>> Values(int definitionId, [FromQuery] string recordStatus = "active", [FromQuery] int pageNumber = 1, [FromQuery] int pageSize = 100, CancellationToken cancellationToken = default) => sender.Send(new GetDimensionValuesQuery(definitionId, recordStatus, pageNumber, pageSize), cancellationToken);
    [HttpGet("accounts/{accountId:int}/policies")] [HasPermission(AccountingPermissions.ViewAccountDimensionPolicies)] public Task<IReadOnlyList<AccountDimensionPolicyResponse>> Policies(int accountId, CancellationToken cancellationToken) => sender.Send(new GetAccountDimensionPoliciesQuery(accountId), cancellationToken);
    [HttpPost] [HasPermission(AccountingPermissions.CreateDimensionDefinitions)] public async Task<IActionResult> Create(DimensionDefinitionRequest request, CancellationToken cancellationToken) { var result = await sender.Send(new CreateDimensionDefinitionCommand(request), cancellationToken); return result.IsSuccess ? Ok(result.Value) : result.ToProblem(); }
    [HttpPut("{id:int}")] [HasPermission(AccountingPermissions.EditDimensionDefinitions)] public async Task<IActionResult> Update(int id, DimensionDefinitionRequest request, CancellationToken cancellationToken) { var result = await sender.Send(new UpdateDimensionDefinitionCommand(id, request), cancellationToken); return result.IsSuccess ? Ok(result.Value) : result.ToProblem(); }
    [HttpDelete("{id:int}")] [HasPermission(AccountingPermissions.ArchiveDimensionDefinitions)] public async Task<IActionResult> Archive(int id, RowVersionRequest request, CancellationToken cancellationToken) { var result = await sender.Send(new ArchiveDimensionDefinitionCommand(id, request.RowVersion), cancellationToken); return result.IsSuccess ? NoContent() : result.ToProblem(); }
    [HttpPost("{id:int}/restore")] [HasPermission(AccountingPermissions.RestoreDimensionDefinitions)] public async Task<IActionResult> Restore(int id, RowVersionRequest request, CancellationToken cancellationToken) { var result = await sender.Send(new RestoreDimensionDefinitionCommand(id, request.RowVersion), cancellationToken); return result.IsSuccess ? Ok(result.Value) : result.ToProblem(); }
    [HttpPost("values")] [HasPermission(AccountingPermissions.CreateDimensionValues)] public async Task<IActionResult> CreateValue(DimensionValueRequest request, CancellationToken cancellationToken) { var result = await sender.Send(new CreateDimensionValueCommand(request), cancellationToken); return result.IsSuccess ? Ok(result.Value) : result.ToProblem(); }
    [HttpPut("values/{id:int}")] [HasPermission(AccountingPermissions.EditDimensionValues)] public async Task<IActionResult> UpdateValue(int id, DimensionValueRequest request, CancellationToken cancellationToken) { var result = await sender.Send(new UpdateDimensionValueCommand(id, request), cancellationToken); return result.IsSuccess ? Ok(result.Value) : result.ToProblem(); }
    [HttpDelete("values/{id:int}")] [HasPermission(AccountingPermissions.ArchiveDimensionValues)] public async Task<IActionResult> ArchiveValue(int id, RowVersionRequest request, CancellationToken cancellationToken) { var result = await sender.Send(new ArchiveDimensionValueCommand(id, request.RowVersion), cancellationToken); return result.IsSuccess ? NoContent() : result.ToProblem(); }
    [HttpPost("values/{id:int}/restore")] [HasPermission(AccountingPermissions.RestoreDimensionValues)] public async Task<IActionResult> RestoreValue(int id, RowVersionRequest request, CancellationToken cancellationToken) { var result = await sender.Send(new RestoreDimensionValueCommand(id, request.RowVersion), cancellationToken); return result.IsSuccess ? Ok(result.Value) : result.ToProblem(); }
    [HttpPut("policies")] [HasPermission(AccountingPermissions.EditAccountDimensionPolicies)] public async Task<IActionResult> Policy(AccountDimensionPolicyRequest request, CancellationToken cancellationToken) { var result = await sender.Send(new UpsertAccountDimensionPolicyCommand(request), cancellationToken); return result.IsSuccess ? Ok(result.Value) : result.ToProblem(); }
}
