import { useMemo, useState } from 'react';
import { StyleSheet, View } from 'react-native';
import { useQueryClient } from '@tanstack/react-query';
import { useTranslation } from 'react-i18next';
import { useAppTheme } from '@/src/core/theme';
import { permissions, useAuthorization } from '@/src/features/auth';
import { AppAlert, AppCard, AppSpreadsheetImportView, AppStatusBadge, AppText, type AppAlertSeverity, type SpreadsheetImportPhase } from '@/src/shared/components';
import { useAppReadOnly } from '@/src/shared/contexts/AppReadOnlyContext';
import { isAmbiguousImportError, pickNativeSpreadsheet, shareSpreadsheetTemplate, spreadsheetErrorMessage, type NativeSpreadsheetFile } from '@/src/shared/importing';
import { useBulkCreateOrganizationalItems, useOrganizationalLookup } from '../../queries/use-organizational-structure';
import { organizationalStructureKeys } from '../../queries/organizational-structure-keys';
import type { OrganizationalResource } from '../../types/organizational-structure';
import { getOrganizationalImportHeaders, getOrganizationalImportTemplateFile, getOrganizationalParentResource, ORGANIZATIONAL_IMPORT_MAX_BYTES, ORGANIZATIONAL_IMPORT_MAX_ROWS, parseOrganizationalImport, type OrganizationalImportRow } from './organizational-structure-import';

export function OrganizationalStructureImportView({ resource }: { resource: OrganizationalResource }) {
  const { t } = useTranslation(); const { theme } = useAppTheme(); const queryClient = useQueryClient(); const { isReadOnly, notifyBlockedAction } = useAppReadOnly();
  const { allowed: canCreate } = useAuthorization({ allowSuperAdmin: true, requiredPermissions: [permissions.CreateOrganizationalStructure] });
  const parentResource = getOrganizationalParentResource(resource);
  const parent = useOrganizationalLookup(parentResource ?? 'branches', undefined, Boolean(parentResource));
  const titles = useOrganizationalLookup('job-titles', undefined, resource === 'positions'); const levels = useOrganizationalLookup('job-levels', undefined, resource === 'positions');
  const mutation = useBulkCreateOrganizationalItems();
  const [file, setFile] = useState<NativeSpreadsheetFile | null>(null); const [rows, setRows] = useState<OrganizationalImportRow[]>([]); const [phase, setPhase] = useState<SpreadsheetImportPhase>('idle'); const [feedback, setFeedback] = useState<{ severity: AppAlertSeverity; message: string } | null>(null);
  const headers = getOrganizationalImportHeaders(resource); const counts = useMemo(() => ({ total: rows.length, ready: rows.filter((row) => row.status === 'ready').length, invalid: rows.filter((row) => row.status === 'invalid').length, uploaded: rows.filter((row) => row.status === 'uploaded').length }), [rows]);
  const guard = () => { if (isReadOnly) { notifyBlockedAction(); return false; } if (!canCreate) { setFeedback({ severity: 'error', message: t('spreadsheetImport.permissionDenied') }); return false; } return true; };
  const pick = async () => { if (!guard() || (parentResource && parent.isLoading)) return; try { const selected = await pickNativeSpreadsheet(); if (!selected) return; setPhase('parsing'); setFeedback(null); const parsed = await parseOrganizationalImport(selected, resource, parent.data ?? [], titles.data ?? [], levels.data ?? [], t); setFile(selected); setRows(parsed); setPhase('preview'); const invalid = parsed.filter((row) => row.status === 'invalid').length; setFeedback({ severity: invalid ? 'warning' : 'success', message: t(invalid ? 'spreadsheetImport.previewWithErrors' : 'spreadsheetImport.previewReady', { count: parsed.length, invalid }) }); } catch (error) { setPhase('failed'); setFeedback({ severity: 'error', message: spreadsheetErrorMessage(error, t) }); } };
  const submit = async () => { if (!guard()) return; const pending = rows.filter((row): row is OrganizationalImportRow & { request: NonNullable<OrganizationalImportRow['request']> } => row.status === 'ready' && row.request !== null); if (!pending.length) return; setPhase('submitting'); setFeedback(null); try { const result = await mutation.mutateAsync({ resource, requests: pending.map((row) => row.request) }); const uploaded = new Set(pending.map((row) => row.rowNumber)); setRows((current) => current.map((row) => uploaded.has(row.rowNumber) ? { ...row, status: 'uploaded' } : row)); setPhase('succeeded'); setFeedback({ severity: 'success', message: t('organizationalStructure.import.success', { count: result.createdCount }) }); } catch (error) { const uncertain = isAmbiguousImportError(error); const uploaded = new Set(pending.map((row) => row.rowNumber)); setRows((current) => current.map((row) => uploaded.has(row.rowNumber) ? { ...row, status: uncertain ? 'uncertain' : 'failed' } : row)); setPhase(uncertain ? 'uncertain' : 'failed'); setFeedback({ severity: uncertain ? 'warning' : 'error', message: uncertain ? t('spreadsheetImport.uncertain') : spreadsheetErrorMessage(error, t) }); } };
  const clear = () => { setFile(null); setRows([]); setPhase('idle'); setFeedback(null); }; const reconcile = async () => { await queryClient.invalidateQueries({ queryKey: organizationalStructureKeys.all }); setFeedback({ severity: 'info', message: t('spreadsheetImport.reconciled') }); }; const shareTemplate = async () => { try { await shareSpreadsheetTemplate(headers, getOrganizationalImportTemplateFile(resource)); } catch (error) { setFeedback({ severity: 'error', message: spreadsheetErrorMessage(error, t) }); } };
  return <View style={styles.root}>{parentResource && (parent.isLoading || parent.isError) ? <AppAlert severity={parent.isError ? 'error' : 'info'}>{t(parent.isError ? 'organizationalStructure.import.lookupError' : 'organizationalStructure.import.lookupLoading')}</AppAlert> : null}<AppSpreadsheetImportView counts={counts} feedback={feedback} file={file} headers={headers} maxBytes={ORGANIZATIONAL_IMPORT_MAX_BYTES} maxRows={ORGANIZATIONAL_IMPORT_MAX_ROWS} onClear={clear} onPick={() => void pick()} onReconcile={() => void reconcile()} onShareTemplate={() => void shareTemplate()} onSubmit={() => void submit()} phase={phase} pickDisabled={Boolean(parentResource && (parent.isLoading || parent.isError))} submitDisabled={!canCreate || isReadOnly}>{rows.length ? <View style={styles.rows}>{rows.map((row) => <AppCard key={row.rowNumber} padding="sm" style={styles.row}><View style={styles.rowHeader}><AppText variant="label">{t('spreadsheetImport.row', { number: row.rowNumber })}</AppText><AppStatusBadge color={row.status === 'uploaded' ? theme.colors.success : row.status === 'invalid' || row.status === 'failed' ? theme.colors.danger : theme.colors.primary} label={t(`spreadsheetImport.status.${row.status}`)} /></View><AppText numberOfLines={1} variant="bodySmall">{row.values.nameEn} · {row.values.nameAr}</AppText><AppText color="muted" numberOfLines={1} variant="caption">{row.values.code || '—'} · {row.values.parentCode || '—'}</AppText>{row.error ? <AppText color="danger" variant="caption">{row.error}</AppText> : null}</AppCard>)}</View> : null}</AppSpreadsheetImportView></View>;
}
const styles = StyleSheet.create({ root: { gap: 8 }, rows: { gap: 6 }, row: { gap: 3 }, rowHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8 } });
