<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>ErpSystem.Modules.HR</AssemblyName>
    <RootNamespace>ErpSystem.Modules.HR</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Hangfire.AspNetCore" />
    <ProjectReference Include="..\..\..\BuildingBlocks\ErpSystem.BuildingBlocks.Modularity\ErpSystem.BuildingBlocks.Modularity.csproj" />
    <ProjectReference Include="..\ErpSystem.Modules.HR.Application\ErpSystem.Modules.HR.Application.csproj" />
    <ProjectReference Include="..\ErpSystem.Modules.HR.Infrastructure\ErpSystem.Modules.HR.Infrastructure.csproj" />
    <ProjectReference Include="..\ErpSystem.Modules.HR.Presentation\ErpSystem.Modules.HR.Presentation.csproj" />
  </ItemGroup>
</Project>
