import { useCallback, useEffect, useMemo, useState } from 'react';
import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import { Platform, StyleSheet, View } from 'react-native';
import { useTranslation } from 'react-i18next';
import { ENV } from '@/src/core/config/env';
import { useLocalization } from '@/src/core/localization';
import { permissions, useAuthorization } from '@/src/features/auth';
import { AppAlert, AppButton, AppCard, AppFilterFormButton, AppSelectField, AppTextField, showToast } from '@/src/shared/components';
import { addressTypeReportApi, getAddressTypeReportDisplayName, type GeneratedAddressTypeReport } from '../api/address-type-report-api';
import { useAddressTypeReportCatalog } from '../queries/use-address-type-reports';

export function AddressTypeReportView() {
  const { t } = useTranslation(); const { allowed, isLoading } = useAuthorization({ requiredPermissions: [permissions.ViewCrystalReports] });
  if (isLoading) return <AppCard padding="md" style={styles.card} variant="outlined"><AppAlert severity="info">{t('feedback.loading')}</AppAlert></AppCard>;
  if (!allowed) return <AppCard padding="md" style={styles.card} variant="outlined"><AppAlert severity="warning">{t('addressTypes.reportPermissionDenied')}</AppAlert></AppCard>;
  return <AuthorizedAddressTypeReportView />;
}
function AuthorizedAddressTypeReportView() {
  const { t } = useTranslation(); const { isRTL } = useLocalization(); const language = isRTL ? 'ar' : 'en'; const catalog = useAddressTypeReportCatalog(ENV.isApiConfigured); const reports = useMemo(() => catalog.data ?? [], [catalog.data]);
  const [selectedReportId, setSelectedReportId] = useState<string | null>(null); const [nameAr, setNameAr] = useState(''); const [nameEn, setNameEn] = useState(''); const [draftAr, setDraftAr] = useState(''); const [draftEn, setDraftEn] = useState(''); const [generating, setGenerating] = useState(false); const [generated, setGenerated] = useState<GeneratedAddressTypeReport | null>(null); const selected = reports.find((report) => report.id === selectedReportId) ?? reports[0] ?? null;
  useEffect(() => () => generated?.dispose(), [generated]);
  const open = useCallback(async (report: GeneratedAddressTypeReport) => { if (Platform.OS === 'web') { window.open(report.uri, '_blank', 'noopener,noreferrer'); return; } await Print.printAsync({ uri: report.uri }); }, []);
  const generate = useCallback(async () => { if (!ENV.isApiConfigured || !selected) return; setGenerating(true); try { const report = await addressTypeReportApi.generate({ language, nameAr, nameEn, report: selected }); setGenerated(report); showToast.success(t('addressTypes.reportGenerated')); await open(report); } catch (error) { showToast.error(error, t('addressTypes.reportGenerateFailed')); } finally { setGenerating(false); } }, [language, nameAr, nameEn, open, selected, t]);
  const share = useCallback(async () => { if (!generated) return; try { if (Platform.OS === 'web') { const anchor = document.createElement('a'); anchor.href = generated.uri; anchor.download = generated.fileName; anchor.click(); return; } if (!(await Sharing.isAvailableAsync())) throw new Error(t('addressTypes.reportShareUnavailable')); await Sharing.shareAsync(generated.uri, { dialogTitle: generated.fileName, mimeType: 'application/pdf' }); } catch (error) { showToast.error(error, t('addressTypes.reportGenerateFailed')); } }, [generated, t]);
  const options = useMemo(() => reports.map((report) => ({ value: report.id, label: getAddressTypeReportDisplayName(report, language), icon: 'document-text-outline' as const })), [language, reports]); const count = Number(Boolean(nameAr.trim())) + Number(Boolean(nameEn.trim()));
  return <AppCard padding="md" style={styles.card} variant="outlined">{catalog.isError ? <View style={styles.feedback}><AppAlert severity="warning">{t('addressTypes.reportCatalogError')}</AppAlert><AppButton icon="refresh-outline" onPress={() => void catalog.refetch()} variant="outline">{t('common.retry')}</AppButton></View> : null}{!catalog.isLoading && !catalog.isError && reports.length === 0 ? <AppAlert severity="info">{t('addressTypes.reportUnavailable')}</AppAlert> : null}<AppSelectField allowWhenReadOnly disabled={!ENV.isApiConfigured || catalog.isLoading || !reports.length} label={t('addressTypes.reportType')} leadingIcon="document-text-outline" onChange={(value) => setSelectedReportId(value as string)} options={options} value={selected?.id ?? null} /><AppFilterFormButton activeCount={count} buttonLabel={t('addressTypes.searchReport')} clearDisabled={!draftAr && !draftEn} disabled={!ENV.isApiConfigured || !selected} display="button" icon="search-outline" modalTitle={t('addressTypes.reportFilters')} onApply={() => { setNameAr(draftAr.trim()); setNameEn(draftEn.trim()); }} onClear={() => { setDraftAr(''); setDraftEn(''); }} onOpen={() => { setDraftAr(nameAr); setDraftEn(nameEn); }}><AppTextField allowWhenReadOnly label={t('addressTypes.reportNameEn')} leadingIcon="search-outline" onChangeText={setDraftEn} onClear={() => setDraftEn('')} value={draftEn} /><AppTextField allowWhenReadOnly label={t('addressTypes.reportNameAr')} leadingIcon="search-outline" onChangeText={setDraftAr} onClear={() => setDraftAr('')} value={draftAr} /></AppFilterFormButton><View style={styles.actions}><AppButton disabled={!ENV.isApiConfigured || !selected} fullWidth icon="document-text-outline" loading={generating} onPress={() => void generate()}>{generating ? t('addressTypes.generatingReport') : t('addressTypes.generateReport')}</AppButton></View>{generated ? <View style={styles.generated}><AppAlert severity="success">{t('addressTypes.reportReady')}</AppAlert><AppButton fullWidth icon="print-outline" onPress={() => void open(generated)} variant="outline">{t('addressTypes.openReport')}</AppButton><AppButton fullWidth icon="share-outline" onPress={() => void share()} variant="outline">{t('addressTypes.shareReport')}</AppButton></View> : null}</AppCard>;
}
const styles = StyleSheet.create({ card: { width: '100%', gap: 12 }, feedback: { gap: 8 }, actions: { width: '100%', gap: 8 }, generated: { gap: 8 } });
